(function () {
  "use strict";
  const details = {
    logical:["CST212 > Week 3 > Logical Modeling","Logical Model / Modelo logico","Describes what the system logically does and how information and processes behave without selecting a technology.",["Logical Model != Physical Design","Validated requirements are the input","Correct the model before building"]],
    context:["CST212 > Week 3 > Logical Modeling > Context Diagram","Context Diagram / Diagrama de contexto","Formalizes the Week 1 system boundary as one system process, external entities and crossing data flows.",["One system/process","External entities","Inbound and outbound flows"]],
    dfd:["CST212 > Week 3 > Logical Modeling > DFD","Data Flow Diagram / DFD","Represents movement and transformation of data, not control sequence.",["External entity","Process","Data flow","Data store"]],
    levels:["CST212 > Week 3 > DFD > Levels","Context > Diagram 0 > Child","Semantic zoom reveals the overview, major processes and then one decomposed process.",["Context: territory","Diagram 0: major processes","Child: one process"]],
    balancing:["CST212 > Week 3 > DFD > Balancing","DFD Balancing / Equilibrio","Parent and child external flows must remain consistent.",["A road entering the city cannot disappear when zooming in","Compare parent and child inputs/outputs"]],
    dictionary:["CST212 > Week 3 > Data Dictionary","Data Dictionary / Diccionario","The DFD shows where data moves; the dictionary explains what it means and contains.",["ORDER / PEDIDO","order_id, customer_id, date","products, quantities, price, total"]],
    logic:["CST212 > Week 3 > Process / Decision Logic","Process and Decision Logic","Complementary tools describe sequence, structured logic, condition/action combinations and decision paths.",["Flowchart: sequence","Pseudocode: logic","Decision Table: combinations","Decision Tree: paths"]],
    lenses:["CST212 > Week 3 > Multiple Lenses","One System, Multiple Models","The models are complementary lenses, not competitors.",["Boundary: Context","Movement: DFD","Meaning: Dictionary","Logic: flowchart, pseudocode, table, tree"]],
    asis:["CST212 > Week 3 > Systemic / AI-First","AS-IS > Analysis > TO-BE","Compare the current system with a candidate improved state without assuming shorter is automatically better.",["Risk and compliance","Security and resilience","Quality and user impact"]],
    ai:["CST212 > Week 3 > AI-Assisted Modeling","AI-Generated = Candidate Model","AI may propose models, but stakeholder, requirements, evidence, source-system and human validation remain required.",["Candidate boundary and DFD","Candidate dictionary and logic","Bottleneck hypotheses"]],
    dfdkg:["CST212 > Week 3 > Representation","DFD != Knowledge Graph","A DFD represents data movement; a knowledge graph represents concepts and semantic relationships.",["This map is closer to a learning graph","The representations do not replace each other"]],
    gate:["CST212 > Week 3 > Learning Transfer","Logical System Modeling Gate","Prevents a direct Requirements to Code jump by requiring logical understanding first.",["Boundary and context","Flows and definitions","Logic and consistency","Human acceptance"]]
  };
  const node=(a,b,c)=>c?`<button class="journey-ref-node" type="button" data-concept="${c}">${a}<small>${b}</small></button>`:`<div class="journey-ref-node">${a}<small>${b}</small></div>`;
  const down='<span class="journey-progress-arrow">↓</span>';
  const vertical=items=>items.map((x,i)=>node(...x)+(i<items.length-1?down:"")).join("");
  function week3(learn){
    const s=document.createElement("section");s.id="week3KnowledgeRegion";s.className="week3-native-region";s.dataset.provenance="CST212_CANONICAL_WEEK_3";
    s.innerHTML=`<header class="week3-heading"><span>WEEK 3 / SEMANA 3 · LOGICAL MODELING</span><h2>How does the system work logically?</h2><p>Como funciona logicamente el sistema? Understand data, processes and decisions before selecting technology.</p></header><div class="week3-spine">
    ${node("VALIDATED REQUIREMENTS","Requisitos validados")}${down}<button class="week3-node" data-concept="logical">LOGICAL MODEL<small>Modelo logico</small></button>${down}<button class="week3-node" data-concept="context">SYSTEM BOUNDARY → CONTEXT DIAGRAM<small>Frontera formal</small></button>${down}
    <div class="week3-dfd-system"><div class="week3-group-label">DATA MOVEMENT / MOVIMIENTO DE DATOS</div><button class="week3-node" data-concept="dfd">DATA FLOW DIAGRAM<small>DFD ≠ Flowchart</small></button><div class="week3-dfd-elements"><div class="week3-dfd-element">EXTERNAL ENTITY<br>Entidad externa</div><div class="week3-dfd-element">PROCESS<br>Proceso</div><div class="week3-dfd-element">DATA FLOW<br>Flujo</div><div class="week3-dfd-element">DATA STORE<br>Almacen</div></div><div class="week3-branch"><button class="week3-node" data-concept="levels">CONTEXT → DIAGRAM 0 → CHILD<small>Niveles</small></button><button class="week3-node" data-concept="balancing">DFD BALANCING<small>Equilibrio</small></button><button class="week3-node" data-concept="dictionary">DATA DICTIONARY<small>Significado</small></button><button class="week3-node" data-concept="dfdkg">DFD ≠ KNOWLEDGE GRAPH<small>Representacion</small></button></div></div>${down}
    <button class="week3-node" data-concept="logic">PROCESS / DECISION LOGIC<small>Logica complementaria</small></button><div class="week3-branch"><div class="week3-node">FLOWCHART<small>Secuencia</small></div><div class="week3-node">PSEUDOCODE<small>Logica estructurada</small></div><div class="week3-node">DECISION TABLE<small>Combinaciones</small></div><div class="week3-node">DECISION TREE<small>Rutas</small></div></div></div>
    <div class="week3-distinctions"><button class="week3-distinction" data-concept="lenses">ONE SYSTEM · MULTIPLE LENSES</button><button class="week3-distinction" data-concept="asis">AS-IS → TO-BE · AI-FIRST</button><button class="week3-distinction" data-concept="ai">AI MODEL = CANDIDATE MODEL</button></div>`;
    const canvas=learn.querySelector(".journey-canvas")||learn,transfer=canvas.querySelector(".learning-transfer-pipeline");canvas.insertBefore(s,transfer||null);return s;
  }
  function selector(learn,w3){
    const canvas=learn.querySelector(".journey-canvas")||learn,children=[...canvas.children],w2=children.find(x=>x.textContent.includes("WEEK 2 / SEMANA 2")),i2=children.indexOf(w2),i3=children.indexOf(w3);
    children.forEach((x,i)=>{x.dataset.weekRegion=x===w3?"3":i<i2?"1":i<i3?"2":"shared"});
    const nav=document.createElement("nav");nav.className="learn-week-selector";nav.setAttribute("aria-label","Week navigation");
    nav.innerHTML=[["1","Week 1","Semana 1"],["2","Week 2","Semana 2"],["3","Week 3","Semana 3"],["all","All","Todo"]].map(([v,a,b])=>`<button class="learn-week-button" data-learn-week="${v}" aria-pressed="${v==="all"}">${a}<small>${b}</small></button>`).join("");learn.prepend(nav);
    const anchors={"1":children.find(x=>x.dataset.weekRegion==="1"),"2":w2,"3":w3};
    nav.onclick=e=>{const b=e.target.closest("[data-learn-week]");if(!b)return;const value=b.dataset.learnWeek;nav.querySelectorAll("button").forEach(x=>x.setAttribute("aria-pressed",x===b));children.forEach(x=>{const shared=x.dataset.weekRegion==="shared";x.classList.toggle("week-region-muted",value!=="all"&&!shared&&x.dataset.weekRegion!==value);x.classList.toggle("week-region-active",value!=="all"&&x.dataset.weekRegion===value)});if(value==="all")learn.scrollTo({top:0,behavior:"smooth"});else anchors[value]?.scrollIntoView({behavior:"smooth",block:"start"})};
  }
  function journey(learn){
    const learnBtn=[...document.querySelectorAll("button")].find(x=>x.textContent.trim().startsWith("LEARN"));if(!learnBtn)return;const controls=learnBtn.parentElement;controls.style.flexWrap="wrap";controls.style.rowGap=".45rem";
    const tab=learnBtn.cloneNode(true);tab.id="courseJourneyTab";tab.classList.add("course-journey-tab");tab.disabled=false;tab.innerHTML="<span>COURSE JOURNEY</span><small>recorrido</small>";controls.insertBefore(tab,learnBtn);
    const shell=learn.parentElement,views=["learnView","systemView","exploreView"].map(id=>document.getElementById(id)).filter(Boolean),title=document.querySelector("#detailTitle"),native=title&&(title.closest("aside")||title.parentElement?.parentElement);
    const v=document.createElement("section");v.id="courseJourneyView";v.className="course-journey-view";v.hidden=true;
    const stage=(w,label,q,sub,content)=>`<section class="journey-stage" data-week="${w}"><div class="journey-stage-marker">0${w}</div><div class="journey-stage-content"><div class="journey-stage-label">${label}</div><h2>${q}</h2><p class="journey-stage-question">${sub}</p>${content}</div></section>`;
    const w1=vertical([["NEED / OPPORTUNITY","Necesidad / oportunidad"],["PROBLEM","Problema"],["PROBLEM FRAMING","Formulacion"],["ALTERNATIVES","Alternativas"],["FEASIBILITY","Viabilidad"],["GO / REFRAME / STOP","Decision"]]);
    const w2=`<div class="journey-vertical-flow">${node("STAKEHOLDERS","Interesados")}${down}${node("FACT FINDING","Recopilacion")}${down}${node("REQUIREMENTS","Requisitos")}<div class="journey-split"><div class="journey-branch"><div class="journey-stage-label">SYSTEM VIEW</div>${node("FDD","Funciones")}</div><div class="journey-branch"><div class="journey-stage-label">PROJECT VIEW</div>${node("WBS / EDT","Tareas")}${down}${node("DEPENDENCIES","Dependencias")}${down}${node("CRITICAL PATH","Ruta critica")}</div></div></div>`;
    const w3=`<div class="journey-vertical-flow">${vertical([["VALIDATED REQUIREMENTS","Requisitos validados"],["LOGICAL MODEL","Modelo logico","logical"],["SYSTEM BOUNDARY / CONTEXT","Frontera formal","context"],["DATA FLOW DIAGRAM","Movimiento de datos","dfd"],["DATA DICTIONARY","Significado","dictionary"],["PROCESS / DECISION LOGIC","Logica","logic"]])}<div class="journey-split"><div class="journey-branch">${node("DFD LEVELS + BALANCING","Jerarquia y consistencia","balancing")}</div><div class="journey-branch">${node("FLOWCHART · PSEUDOCODE · TABLE · TREE","Lentes logicos","lenses")}</div></div></div>`;
    v.innerHTML=`<header class="course-journey-header"><span>COURSE JOURNEY / RECORRIDO DEL CURSO</span><h1>One evolving system of knowledge.</h1><p>From organizational need to validated requirements and a logical understanding of the system.</p></header><div class="course-journey-layout"><main class="journey-backbone">${stage(1,"WEEK 1 · PLANNING","WHY? / POR QUE?","Should this initiative exist?",'<div class="journey-vertical-flow">'+w1+"</div>")}${stage(2,"WEEK 2 · PROJECT + ANALYSIS","WHAT DO WE NEED?","Que necesitamos y como organizamos el trabajo?",w2)}${stage(3,"WEEK 3 · LOGICAL MODELING","HOW DOES IT WORK LOGICALLY?","Como funciona logicamente el sistema?",w3)}</main><aside class="journey-detail-panel"><div class="journey-detail-level">SEMANTIC ZOOM</div><div class="journey-breadcrumb">CST212 &gt; Course Journey</div><h3>Select a concept</h3><p>Choose a node to reveal meaning while keeping its relationships visible.</p><div class="journey-detail-points"></div><button class="journey-zoom-out">Back / Zoom out</button></aside></div>`;shell.insertBefore(v,learn);
    const panel=v.querySelector(".journey-detail-panel");v.onclick=e=>{const el=e.target.closest("[data-concept]");if(!el||!details[el.dataset.concept])return;const d=details[el.dataset.concept];v.querySelectorAll(".journey-ref-node").forEach(x=>x.classList.remove("is-focused"));el.classList.add("is-focused");panel.querySelector(".journey-breadcrumb").textContent=d[0];panel.querySelector("h3").textContent=d[1];panel.querySelector("p").textContent=d[2];panel.querySelector(".journey-detail-points").innerHTML=d[3].map(x=>`<div class="journey-detail-point">${x}</div>`).join("");el.scrollIntoView({behavior:"smooth",block:"center"})};
    panel.querySelector(".journey-zoom-out").onclick=()=>{v.querySelectorAll(".journey-ref-node").forEach(x=>x.classList.remove("is-focused"));panel.querySelector(".journey-breadcrumb").textContent="CST212 > Course Journey";panel.querySelector("h3").textContent="Select a concept";panel.querySelector("p").textContent="Choose a node to reveal meaning while keeping its relationships visible.";panel.querySelector(".journey-detail-points").innerHTML=""};
    const leave=()=>{v.hidden=true;if(native)native.hidden=false;tab.classList.remove("active");tab.setAttribute("aria-selected","false")};[...controls.querySelectorAll("button")].filter(x=>x!==tab).forEach(x=>x.addEventListener("click",leave));
    tab.onclick=()=>{views.forEach(x=>x.hidden=true);if(native)native.hidden=true;[...controls.querySelectorAll("button")].forEach(x=>{x.classList.remove("active");x.setAttribute("aria-selected","false")});tab.classList.add("active");tab.setAttribute("aria-selected","true");v.hidden=false;v.scrollTo({top:0,behavior:"smooth"})};
  }
  function nativeDetails(learn){const title=document.querySelector("#detailTitle"),content=document.querySelector("#detailContent");if(!title||!content)return;learn.onclick=e=>{const el=e.target.closest("[data-concept]");if(!el||!details[el.dataset.concept])return;const d=details[el.dataset.concept];learn.querySelectorAll(".week3-node,.week3-distinction").forEach(x=>x.classList.remove("is-focused"));el.classList.add("is-focused");title.textContent=d[1];content.innerHTML=`<dt>BREADCRUMB / RUTA</dt><dd>${d[0]}</dd><dt>DEFINITION / DEFINICION</dt><dd>${d[2]}</dd><dt>CONNECTIONS / CONEXIONES</dt><dd>${d[3].join(" · ")}</dd><dt>SOURCE / PROCEDENCIA</dt><dd>CST212 WEEK 3</dd>`;el.scrollIntoView({behavior:"smooth",block:"center"})}}
  function init(){const learn=document.querySelector("#learnView");if(document.querySelector("#courseJourneyView"))return;if(!learn||!learn.textContent.includes("WEEK 2 / SEMANA 2")){setTimeout(init,60);return}const w3=week3(learn);selector(learn,w3);nativeDetails(learn);journey(learn)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();

