(function () {
  'use strict';

  const t = (es, en) => ({ es, en });
  const db = window.CST212_W4 = { concepts: {}, diagrams: [], sources: {
    course: t('CST212 ES_A190, Semana 4: temas y diseño pedagógico aportados por el usuario. Los elementos concretos del escenario Campus Bikes son ilustrativos hasta contrastarlos con el caso oficial.', 'CST212 ES_A190, Week 4: topics and learning design supplied by the user. Concrete Campus Bikes scenario details are illustrative until checked against the official case.'),
    extension: t('Extensión AI-First derivada del diseño pedagógico de CST212. Propuesta para análisis; requiere validación humana.', 'AI-First extension derived from the CST212 learning design. A proposal for analysis that requires human validation.')
  }};

  function concept(id, layer, label, what, why, how, example, notConfuse, related) {
    db.concepts[id] = { id, layer, label, what, why, how, example, notConfuse,
      related: related || [], source: layer === 'ai' ? 'extension' : 'course' };
  }
  function relation(id, from, to, label, meaning, example) {
    const source = db.concepts[from];
    const target = db.concepts[to];
    concept(id, 'deepening', label, meaning,
      t('Explica una relación verificable entre conceptos, no solo una línea decorativa.', 'It explains a checkable relationship between concepts, not a decorative line.'),
      t('Vincula ' + source.label.es + ' con ' + target.label.es + ' mediante la acción indicada.', 'It links ' + source.label.en + ' to ' + target.label.en + ' through the stated action.'),
      example,
      t('La conexión expresa significado; no establece por sí sola una decisión técnica ni una regla nueva.', 'The link conveys meaning; by itself it does not establish a technical choice or new rule.'), [from, to]);
    return { id, from, to, label };
  }

  concept('object','foundation',t('Objeto','Object'),t('Elemento identificable del dominio al que se atribuyen datos y comportamiento.','An identifiable domain element to which data and behavior are assigned.'),t('Permite comprender participantes concretos del sistema.','It helps us understand concrete participants in the system.'),t('Conserva atributos y responde a operaciones definidas por su clase.','It holds attributes and responds to operations defined by its class.'),t('Una bicicleta concreta sirve como objeto ilustrativo en Campus Bikes.','A specific bicycle is an illustrative object in Campus Bikes.'),t('Un objeto concreto no es la clase que lo describe.','A concrete object is not the class describing it.'),['class','attribute','method']);
  concept('class','foundation',t('Clase','Class'),t('Descripción compartida de un tipo de objetos.','A shared description of a type of objects.'),t('Organiza características y comportamiento comunes sin repetir su definición.','It organizes common characteristics and behavior without repeating their definition.'),t('Define atributos y operaciones que podrán tener sus instancias.','It defines attributes and operations its instances may have.'),t('Bicicleta se usa aquí como clase candidata para el ejemplo didáctico.','Bicycle is used here as a candidate class for the teaching example.'),t('Una clase de análisis no es automáticamente una tabla de base de datos.','An analysis class is not automatically a database table.'),['object','instance','attribute','method']);
  concept('instance','foundation',t('Instancia','Instance'),t('Objeto concreto creado o reconocido a partir de una clase.','A concrete object created or identified from a class.'),t('Permite separar el concepto general de cada participante particular.','It separates a general concept from each particular participant.'),t('Sigue la estructura de su clase y mantiene sus propios valores.','It follows its class structure and has its own values.'),t('Bicicleta A es una instancia ilustrativa de Bicicleta.','Bicycle A is an illustrative instance of Bicycle.'),t('El identificador ilustrativo no afirma que el caso real utilice ese registro.','The illustrative identifier does not claim the real case uses that record.'),['class','object']);
  concept('attribute','foundation',t('Atributo','Attribute'),t('Dato que describe una característica o estado de un objeto.','A piece of data describing an object characteristic or state.'),t('Hace explícita la información que necesita conocer el modelo.','It makes the information needed by the model explicit.'),t('Cada instancia puede conservar un valor según la definición de su clase.','Each instance may hold a value according to its class definition.'),t('Un estado de disponibilidad es un atributo candidato, sujeto a validación.','Availability status is a candidate attribute, subject to validation.'),t('Un atributo no es una acción ni una decisión de interfaz.','An attribute is not an action or a user interface decision.'),['object','class','method']);
  concept('method','foundation',t('Método','Method'),t('Comportamiento u operación disponible para un objeto.','Behavior or an operation available to an object.'),t('Permite ubicar qué responsabilidad ejecuta cada objeto.','It helps locate which responsibility each object performs.'),t('Se invoca mediante una interacción y puede consultar o cambiar estado según las reglas.','It is invoked through an interaction and may read or change state according to rules.'),t('Consultar disponibilidad es un comportamiento candidato del ejemplo didáctico.','Check availability is a candidate behavior in the teaching example.'),t('Un método no es un atributo ni confirma por sí solo una regla del negocio.','A method is not an attribute and does not by itself confirm a business rule.'),['object','attribute','message']);

  concept('responsibility','foundation',t('Responsabilidad','Responsibility'),t('Parte del trabajo o conocimiento que se espera de un objeto.','The work or knowledge expected of an object.'),t('Ayuda a evitar objetos que hacen todo o ninguno que responda por una tarea.','It avoids objects doing everything or leaving work without an owner.'),t('Se asigna al participante que cuenta con la información o comportamiento pertinente.','It is assigned to the participant with the relevant information or behavior.'),t('Una consulta candidata solicita información; otro objeto puede aportar el estado consultado.','A candidate query asks for information; another object may provide the queried status.'),t('Responsabilidad no equivale a puesto de trabajo de una persona.','An object responsibility is not a person’s job title.'),['object','message']);
  concept('message','foundation',t('Mensaje','Message'),t('Solicitud de colaboración de un objeto o participante a otro.','A request for collaboration from one object or participant to another.'),t('Explica cómo varias responsabilidades se coordinan para un resultado.','It explains how responsibilities combine to produce a result.'),t('El emisor solicita una operación y el receptor responde según su responsabilidad.','The sender requests an operation and the receiver responds according to its responsibility.'),t('Una consulta ilustrativa pide conocer la disponibilidad antes de informar una respuesta.','An illustrative query requests availability before reporting a result.'),t('Mensaje de objetos no significa necesariamente paquete de red.','An object message does not necessarily mean a network packet.'),['responsibility','method','sequence']);
  concept('encapsulation','foundation',t('Encapsulación','Encapsulation'),t('Organización del acceso al estado y comportamiento internos de un objeto.','Organization of access to an object’s internal state and behavior.'),t('Permite colaborar sin depender de detalles internos innecesarios.','It allows collaboration without depending on unnecessary internal details.'),t('Otros objetos usan operaciones conocidas en lugar de alterar cualquier dato directamente.','Other objects use known operations instead of changing arbitrary data directly.'),t('Una consulta pide un resultado sin asumir cómo se conserva internamente la disponibilidad.','A query requests a result without assuming how availability is stored internally.'),t('Encapsulación no equivale por sí sola a seguridad informática.','Encapsulation by itself is not computer security.'),['message','attribute','method']);
  concept('polymorphism','foundation',t('Polimorfismo','Polymorphism'),t('Posibilidad de que diferentes objetos respondan a una operación compartida de maneras apropiadas a su tipo.','The ability of different objects to respond to a shared operation in ways appropriate to their type.'),t('Permite comprender variaciones de comportamiento sin forzar un único procedimiento para todos.','It helps explain behavioral variation without forcing one procedure on everything.'),t('La misma solicitud puede producir respuestas especializadas cuando el modelo justifica variantes.','The same request can produce specialized responses when the model justifies variants.'),t('Como analogía didáctica, distintos instrumentos interpretan una misma indicación a su manera.','As a teaching analogy, different instruments interpret the same instruction in their own way.'),t('La analogía no afirma que Campus Bikes tenga subclases específicas.','The analogy does not assert that Campus Bikes has specific subclasses.'),['message','class','method']);

  concept('uml','foundation',t('UML','UML'),t('Lenguaje visual para representar aspectos de un sistema mediante vistas complementarias.','A visual language for representing aspects of a system through complementary views.'),t('Permite comunicar y comprobar modelos que solo con palabras podrían quedar ambiguos.','It helps communicate and check models that words alone might leave ambiguous.'),t('Se elige una vista según la pregunta: objetivos, estructura o comportamiento.','A view is chosen according to the question: goals, structure, or behavior.'),t('En Campus Bikes, las mismas necesidades pueden verse como casos de uso, clases o interacciones.','In Campus Bikes, the same needs can be seen as use cases, classes, or interactions.'),t('UML no es una metodología de desarrollo ni un sistema nuevo.','UML is neither a development methodology nor a new system.'),['usecase','classdiagram','sequence','state','activity']);
  concept('actor','foundation',t('Actor','Actor'),t('Papel externo que interactúa con el sistema para conseguir un objetivo.','An external role that interacts with the system to achieve a goal.'),t('Aclara a quién sirve una función y dónde se sitúa el límite del sistema.','It clarifies whom a function serves and where the system boundary lies.'),t('Inicia o participa en un caso de uso desde fuera del límite dibujado.','It starts or participates in a use case from outside the drawn boundary.'),t('Cliente es un actor candidato para la consulta didáctica de Campus Bikes.','Customer is a candidate actor for the Campus Bikes teaching query.'),t('Un actor no tiene que ser una persona concreta.','An actor need not be a specific person.'),['goal','usecase','boundary']);
  concept('goal','foundation',t('Objetivo del actor','Actor goal'),t('Resultado que un actor espera alcanzar al usar el sistema.','An outcome an actor hopes to achieve by using the system.'),t('Evita confundir el propósito del usuario con una pantalla o un botón.','It prevents confusing a user purpose with a screen or button.'),t('Se expresa como una necesidad observable y se relaciona con un caso de uso.','It is expressed as an observable need and related to a use case.'),t('Conocer disponibilidad es el objetivo ilustrativo de la consulta.','Learning availability is the illustrative query goal.'),t('El ejemplo no añade un requisito confirmado al caso oficial.','The example does not add a confirmed requirement to the official case.'),['actor','usecase']);
  concept('usecase','foundation',t('Caso de uso','Use case'),t('Representación de un objetivo que un actor alcanza mediante interacciones con el sistema.','A representation of a goal an actor reaches through interactions with the system.'),t('Relaciona necesidades con capacidades observables antes de diseñar pantallas.','It connects needs to observable capabilities before designing screens.'),t('El actor participa en el escenario y el sistema responde dentro de su límite.','An actor participates in a scenario and the system responds within its boundary.'),t('Consultar disponibilidad sirve como caso de uso ilustrativo.','Check availability serves as an illustrative use case.'),t('Un caso de uso no es una pantalla ni un diagrama de flujo de datos.','A use case is neither a screen nor a data flow diagram.'),['actor','goal','boundary','uml']);
  concept('boundary','foundation',t('Límite del sistema','System boundary'),t('Distinción entre lo que pertenece al sistema modelado y su entorno.','The distinction between the modeled system and its environment.'),t('Evita atribuir al sistema las acciones de sus actores externos.','It avoids assigning external actors’ actions to the system.'),t('En casos de uso, rodea las capacidades del sistema mientras actores permanecen fuera.','In use cases, it encloses system capabilities while actors remain outside.'),t('El Cliente del escenario está fuera; Consultar disponibilidad está dentro del límite ilustrativo.','The scenario Customer is outside; Check availability is inside the illustrative boundary.'),t('El borde visual no establece por sí solo alcance aprobado.','A visual boundary by itself does not establish approved scope.'),['actor','usecase']);

  concept('classdiagram','foundation',t('Diagrama de clases','Class diagram'),t('Vista UML de clases, atributos, operaciones y relaciones estructurales.','A UML view of classes, attributes, operations, and structural relationships.'),t('Permite razonar sobre responsabilidades y vínculos antes de construir la solución.','It allows reasoning about responsibilities and links before building the solution.'),t('Presenta tipos y relaciones con suficiente detalle para revisar el modelo.','It shows types and relationships with enough detail to review the model.'),t('Cliente, Consulta y Bicicleta son clases candidatas ilustrativas de Campus Bikes.','Customer, Query, and Bicycle are illustrative candidate Campus Bikes classes.'),t('No es automáticamente un esquema de tablas ni una implementación.','It is not automatically a table schema or implementation.'),['class','association','operation']);
  concept('association','foundation',t('Relación entre clases','Class relationship'),t('Vínculo estructural significativo entre clases del modelo.','A meaningful structural link between model classes.'),t('Hace visibles dependencias del dominio que deben poder explicarse.','It makes domain dependencies visible so they can be explained.'),t('Se conecta solo cuando su significado y dirección pueden describirse.','It is connected only when its meaning and direction can be described.'),t('Consulta se relaciona con Bicicleta en el ejemplo porque pregunta por ella.','Query relates to Bicycle in the example because it asks about it.'),t('Una línea sin significado no prueba que el vínculo sea válido.','An unexplained line does not prove the link is valid.'),['classdiagram','class']);
  concept('operation','foundation',t('Operación','Operation'),t('Comportamiento nombrado en una clase que sus objetos pueden ofrecer.','Behavior named in a class that its objects may provide.'),t('Permite asignar una responsabilidad de comportamiento al tipo apropiado.','It helps assign behavioral responsibility to the right type.'),t('Otros participantes solicitan la operación a través de mensajes.','Other participants request the operation through messages.'),t('Obtener estado es una operación candidata del ejemplo.','Get status is a candidate operation in the example.'),t('Una operación de análisis no fija un método técnico concreto.','An analysis operation does not fix a concrete technical method.'),['classdiagram','message','method']);

  concept('scenario','foundation',t('Un mismo escenario','One scenario'),t('Secuencia de hechos y decisiones que se mantiene fija al cambiar de vista.','A sequence of events and decisions kept fixed while changing views.'),t('Permite comparar representaciones sin cambiar el problema que se estudia.','It lets learners compare representations without changing the studied problem.'),t('Se observa por tiempo, por estados y por actividades.','It is viewed by time, by states, and by activities.'),t('Consulta ilustrativa de disponibilidad en Campus Bikes, sin reglas adicionales afirmadas.','An illustrative Campus Bikes availability query, with no extra rules asserted.'),t('Cambiar de representación no crea otro sistema ni otro caso.','Changing representation does not create another system or case.'),['sequence','state','activity']);
  concept('sequence','foundation',t('Diagrama de secuencia','Sequence diagram'),t('Vista UML de participantes y mensajes ordenados en el tiempo.','A UML view of participants and time-ordered messages.'),t('Aclara quién pide qué a quién y cuándo dentro del mismo escenario.','It clarifies who requests what from whom and when in the same scenario.'),t('Sitúa participantes como líneas de vida y ordena los mensajes entre ellos.','It lays out participants as lifelines and orders messages between them.'),t('Cliente solicita una consulta; el sistema revisa información y devuelve una respuesta ilustrativa.','Customer requests a query; the system checks information and returns an illustrative response.'),t('No representa estados internos ni un flujo de datos DFD.','It does not represent internal states or a DFD data flow.'),['scenario','message','state','activity']);
  concept('state','foundation',t('Diagrama de estados','State diagram'),t('Vista de estados de un objeto y de los eventos que provocan cambios.','A view of an object’s states and the events causing change.'),t('Muestra el ciclo de vida del mismo objeto dentro del escenario.','It shows the same object’s lifecycle within the scenario.'),t('Conecta cada estado mediante transiciones justificadas por eventos.','It links states through transitions justified by events.'),t('La Consulta ilustrativa pasa de recibida a en revisión y respondida.','The illustrative Query moves from received to under review to answered.'),t('Los nombres de estado son ilustrativos y no reglas oficiales de Campus Bikes.','The state names are illustrative, not official Campus Bikes rules.'),['scenario','transition','sequence','activity']);
  concept('transition','foundation',t('Transición','Transition'),t('Cambio entre estados provocado por un evento o condición definida.','A change between states caused by a defined event or condition.'),t('Evita que estados parezcan casillas sin explicación de cambio.','It prevents states from looking like boxes with no explanation for change.'),t('Sale de un estado y entra en otro cuando ocurre el evento.','It leaves one state and enters another when its event occurs.'),t('Registrar la consulta inicia la revisión en el ejemplo didáctico.','Recording the query starts review in the teaching example.'),t('Una flecha sola no establece un evento real del negocio.','An arrow alone does not establish a real business event.'),['state','scenario']);
  concept('activity','foundation',t('Diagrama de actividad','Activity diagram'),t('Vista del trabajo como acciones y decisiones relacionadas.','A view of work as related actions and decisions.'),t('Muestra qué trabajo sucede en el escenario sin confundirlo con mensajes o estados.','It shows the scenario work without confusing it with messages or states.'),t('Conecta acciones desde el inicio hasta el resultado, mostrando caminos cuando existen reglas.','It links actions from start to outcome, showing paths when rules exist.'),t('Registrar consulta, revisar información e informar respuesta son acciones ilustrativas.','Record query, review information, and report result are illustrative actions.'),t('No sustituye al DFD ni afirma un camino de excepción desconocido.','It does not replace a DFD or assert an unknown exception path.'),['scenario','sequence','state','decisionpoint']);
  concept('decisionpoint','foundation',t('Decisión de actividad','Activity decision'),t('Punto donde una condición conocida dirige caminos distintos.','A point where a known condition directs different paths.'),t('Permite visualizar alternativas sin inventar resultados.','It helps visualize alternatives without inventing outcomes.'),t('Cada salida necesita una condición o pregunta justificada por el escenario.','Each outgoing path needs a condition or question justified by the scenario.'),t('Disponibilidad conocida o pendiente de confirmar podría ser una pregunta candidata, no una regla afirmada.','Known or pending availability could be a candidate question, not an asserted rule.'),t('No asumir respuestas Sí/No cuando el caso no define esa condición.','Do not assume Yes/No outcomes when the case does not define the condition.'),['activity','scenario']);

  concept('need','foundation',t('Necesidad','Need'),t('Resultado o mejora que motiva examinar alternativas.','An outcome or improvement motivating the examination of alternatives.'),t('Impide empezar por una herramienta sin tener claro el problema.','It prevents starting from a tool without understanding the problem.'),t('Se contrasta con el proceso actual, evidencia y objetivos.','It is checked against the current process, evidence, and goals.'),t('El ejercicio de Campus Bikes pregunta cómo atender una consulta de forma adecuada.','The Campus Bikes exercise asks how to handle a query appropriately.'),t('Un deseo de tener una aplicación no es automáticamente una necesidad confirmada.','A wish for an app is not automatically a confirmed need.'),['alternative','processchange']);
  concept('alternative','foundation',t('Alternativa de solución','Solution alternative'),t('Forma candidata de satisfacer la necesidad.','A candidate way to meet the need.'),t('Permite comparar caminos antes de comprometer recursos.','It allows comparing paths before committing resources.'),t('Puede combinar cambios de proceso, herramientas existentes y modos de obtención.','It can combine process changes, existing tools, and ways of obtaining a solution.'),t('Para la consulta de Campus Bikes, se examinan rutas sin elegir aún una.','For the Campus Bikes query, routes are examined without choosing one yet.'),t('Una alternativa candidata no es una decisión aprobada.','A candidate alternative is not an approved decision.'),['need','build','buy','web','outsourcing','offshoring']);
  concept('processchange','deepening',t('Mejora del proceso','Process improvement'),t('Cambio en el trabajo, las reglas o la coordinación sin asumir nuevo software.','A change to work, rules, or coordination without assuming new software.'),t('Una necesidad puede resolverse mejorando el sistema actual.','A need may be addressed by improving the current system.'),t('Se identifican fallas del proceso y se evalúa una intervención apropiada.','Process weaknesses are identified and an appropriate intervention evaluated.'),t('Aclarar quién confirma una consulta sería una posibilidad que requiere evidencia.','Clarifying who confirms a query would be a possibility requiring evidence.'),t('No se presenta como hecho que Campus Bikes tenga esa falla.','This does not claim that Campus Bikes has that weakness.'),['need','alternative']);
  concept('build','foundation',t('Desarrollar · Build','Build'),t('Crear o adaptar capacidades de software mediante trabajo de desarrollo.','Creating or adapting software capabilities through development work.'),t('Puede ofrecer ajuste a necesidades específicas a cambio de trabajo y responsabilidad de entrega.','It may fit specific needs while requiring development work and delivery responsibility.'),t('Se define alcance, equipo, plazo, mantenimiento y criterios de aceptación.','Scope, team, time, maintenance, and acceptance criteria are defined.'),t('Campus Bikes podría evaluar esta ruta; no se declara que sea la elegida.','Campus Bikes could evaluate this route; it is not declared the chosen one.'),t('Desarrollar no implica necesariamente trabajar con equipo interno ni entregar una web.','Build does not necessarily mean using an in-house team or delivering a web app.'),['alternative','buy','outsourcing','web']);
  concept('buy','foundation',t('Adquirir · Buy','Buy'),t('Obtener software o una capacidad existente de un proveedor.','Obtaining existing software or capability from a supplier.'),t('Puede reducir desarrollo propio, aunque exige evaluar adecuación, integración y condiciones.','It may reduce custom development while requiring fit, integration, and terms to be assessed.'),t('Se examina qué necesidades cubre y cuáles siguen pendientes.','Its covered and uncovered needs are examined.'),t('Campus Bikes podría estudiar una capacidad existente, si se dispone de evidencia.','Campus Bikes could examine an existing capability if evidence is available.'),t('Comprar no garantiza que una herramienta resuelva el proceso del negocio.','Buying does not guarantee a tool solves the business process.'),['alternative','build','ownership']);
  concept('web','foundation',t('Sistema web','Web system'),t('Forma de ofrecer interacción con capacidades del sistema mediante tecnologías web.','A way to provide interaction with system capabilities through web technologies.'),t('Ayuda a analizar cómo accederán las personas a la solución.','It helps analyze how people will access a solution.'),t('Relaciona la interacción del usuario con funciones y datos según el diseño elegido.','It connects user interaction with functions and data according to the chosen design.'),t('Una consulta web de disponibilidad sería una posibilidad ilustrativa.','A web availability query would be an illustrative possibility.'),t('Web describe una forma de acceso; no decide por sí sola Build, Buy o outsourcing.','Web describes a form of access; it does not determine Build, Buy, or outsourcing.'),['alternative','build','buy']);
  concept('outsourcing','foundation',t('Externalización · Outsourcing','Outsourcing'),t('Encargar trabajo o servicios a un proveedor externo.','Assigning work or services to an external supplier.'),t('Permite evaluar capacidades externas junto con contrato, coordinación y control.','It brings external capability into consideration with contracts, coordination, and control.'),t('Se definen responsabilidades, entregables y validación del trabajo del proveedor.','Responsibilities, deliverables, and validation of supplier work are defined.'),t('Una parte del desarrollo de Campus Bikes podría encargarse fuera; es solo una alternativa.','Part of Campus Bikes development could be assigned externally; it is only an alternative.'),t('Externalizar responde quién hace el trabajo, no en qué país necesariamente.','Outsourcing answers who does the work, not necessarily which country.'),['alternative','offshoring','control']);
  concept('offshoring','foundation',t('Trabajo en otro país · Offshoring','Offshoring'),t('Ubicar trabajo en otro país, de forma interna o mediante un proveedor.','Locating work in another country, internally or through a supplier.'),t('Hace visible el efecto de ubicación en coordinación, contexto y restricciones.','It exposes the role of location in coordination, context, and constraints.'),t('Se compara dónde se realiza el trabajo además de quién lo realiza.','It compares where work happens in addition to who performs it.'),t('Un equipo en otro país sería una opción a evaluar para Campus Bikes, no un hecho del caso.','A team in another country would be an option to evaluate for Campus Bikes, not a case fact.'),t('Offshoring y outsourcing son ejes distintos y pueden combinarse.','Offshoring and outsourcing are different axes and may be combined.'),['outsourcing','location','alternative']);

  concept('strategy','foundation',t('Estrategia de obtención','Acquisition strategy'),t('Decisión sobre cómo se conseguirán las capacidades necesarias.','A decision about how required capabilities will be obtained.'),t('Une necesidades, alternativas, recursos y responsabilidades.','It links needs, alternatives, resources, and responsibilities.'),t('Compara formas de adquirir capacidades sin confundirlas con canal o ubicación.','It compares ways to obtain capabilities without confusing them with channel or location.'),t('Campus Bikes puede comparar desarrollar, adquirir y colaborar con proveedores.','Campus Bikes can compare building, buying, and working with suppliers.'),t('No se decide solo por moda tecnológica.','It is not decided by technology trends alone.'),['build','buy','web','outsourcing','offshoring']);
  concept('ownership','deepening',t('Responsabilidad y propiedad','Responsibility and ownership'),t('Claridad sobre quién controla activos, cambios y obligaciones de cada alternativa.','Clarity on who controls assets, changes, and obligations for each alternative.'),t('Evita comparar estrategias sin considerar sus compromisos posteriores.','It prevents comparing strategies without later obligations.'),t('Se registran acuerdos y supuestos de cada opción antes de elegir.','Agreements and assumptions for each option are recorded before selection.'),t('Los derechos y obligaciones para Campus Bikes tendrían que establecerse, no suponerse.','Campus Bikes rights and obligations would need to be established, not assumed.'),t('Un proveedor externo no elimina la responsabilidad de la organización.','An external supplier does not remove organizational accountability.'),['strategy','outsourcing','buy']);
  concept('location','deepening',t('Lugar de ejecución','Work location'),t('Ubicación donde se realiza el trabajo necesario para obtener la solución.','The place where work to obtain the solution is performed.'),t('Permite evaluar coordinación y restricciones sin confundir lugar con proveedor.','It helps assess coordination and constraints without confusing location and supplier.'),t('Se examina por separado de cómo se contrata la capacidad.','It is considered separately from how capacity is contracted.'),t('Campus Bikes podría evaluar un equipo local o en otro país, según evidencia.','Campus Bikes could assess a local or foreign team, depending on evidence.'),t('Trabajo en otro país no significa siempre externalización.','Work in another country does not always mean outsourcing.'),['offshoring','outsourcing']);
  concept('control','deepening',t('Control y dependencia','Control and dependency'),t('Capacidad de gobernar cambios y dependencias de una estrategia elegida.','The ability to govern changes and dependencies in a chosen strategy.'),t('Una alternativa ventajosa en costo puede aumentar dependencia o reducir control.','An option favorable on cost may increase dependency or reduce control.'),t('Se comparan condiciones, integración y capacidad de modificar la solución.','Terms, integration, and ability to change the solution are compared.'),t('El análisis de Campus Bikes requeriría datos de cada proveedor real.','A Campus Bikes analysis would require data from each actual supplier.'),t('No se inventan contratos o riesgos confirmados.','No contracts or confirmed risks are invented.'),['strategy','buy','outsourcing']);
  concept('risk','deepening',t('Riesgos y supuestos','Risks and assumptions'),t('Incertidumbres y condiciones que influyen en los resultados esperados.','Uncertainties and conditions affecting expected outcomes.'),t('Evita que la comparación parezca cierta cuando faltan datos.','It prevents comparisons from appearing certain when data is missing.'),t('Cada suposición se hace visible y se comprueba cuando es decisiva.','Each assumption is made visible and checked when it matters.'),t('Costos o tiempos de un proveedor de Campus Bikes requerirían una fuente real.','Costs or timings for a Campus Bikes supplier would require a real source.'),t('Una hipótesis no equivale a evidencia.','A hypothesis is not evidence.'),['strategy','evidence','comparison']);

  concept('evidence','foundation',t('Evidencia','Evidence'),t('Información verificable usada para sustentar una comparación.','Checkable information used to support a comparison.'),t('Permite explicar por qué una opción parece adecuada.','It lets us explain why an option appears suitable.'),t('Se registra su fuente y se conecta con el criterio afectado.','Its source is recorded and linked to the affected criterion.'),t('Una cotización real podría sustentar un costo de Campus Bikes; aquí no se inventa.','A real quote could support a Campus Bikes cost; none is invented here.'),t('Una estimación sin fuente debe señalarse como supuesto.','An estimate without a source must be identified as an assumption.'),['criteria','cost','benefit']);
  concept('criteria','foundation',t('Criterios','Criteria'),t('Reglas de comparación acordadas antes de seleccionar una alternativa.','Comparison rules agreed before selecting an alternative.'),t('Evitan escoger según una preferencia tecnológica sin explicación.','They prevent unexplained technology preferences from deciding.'),t('Se relacionan con necesidades, costos, riesgos y valor esperado.','They relate to needs, costs, risks, and expected value.'),t('Costo, cobertura de necesidades y tiempo serían criterios candidatos para Campus Bikes.','Cost, coverage of needs, and time would be candidate criteria for Campus Bikes.'),t('Los criterios candidatos no han sido aprobados por el caso.','Candidate criteria are not approved case criteria.'),['evidence','comparison','decision']);
  concept('cost','foundation',t('Costos','Costs'),t('Recursos que exige obtener, operar y mantener una alternativa.','Resources required to obtain, operate, and maintain an alternative.'),t('Una compra inicial puede tener costos posteriores relevantes.','An initial purchase may involve material later costs.'),t('Se describen tipos, montos, periodos y fuente cuando existan datos.','Types, amounts, periods, and sources are described when data exists.'),t('No se asigna una cifra de costo a Campus Bikes sin datos aportados.','No cost figure is assigned to Campus Bikes without supplied data.'),t('Costo no equivale por sí solo al valor total de la opción.','Cost alone is not an option’s total value.'),['evidence','benefit','roi','npv']);
  concept('benefit','foundation',t('Beneficios','Benefits'),t('Resultados favorables esperados de una alternativa.','Favorable outcomes expected from an alternative.'),t('Permiten contrastar el esfuerzo invertido con lo que la organización busca mejorar.','They help compare effort with what the organization aims to improve.'),t('Se expresan y se sustentan con medidas o evidencia apropiadas.','They are stated and supported with suitable measures or evidence.'),t('Una consulta más clara para Campus Bikes sería una hipótesis de beneficio, no un resultado medido.','A clearer Campus Bikes query would be a benefit hypothesis, not a measured outcome.'),t('Un beneficio esperado no es un beneficio realizado.','An expected benefit is not a realized benefit.'),['evidence','cost','roi','npv']);
  concept('roi','foundation',t('ROI · retorno sobre inversión','ROI · return on investment'),t('Medida relativa que compara el retorno neto esperado con la inversión considerada.','A relative measure comparing expected net return with the investment considered.'),t('Ayuda a preguntar qué obtiene la organización en relación con lo que invierte.','It helps ask what an organization gains relative to what it invests.'),t('Requiere beneficios y costos definidos bajo supuestos comparables.','It requires benefits and costs defined under comparable assumptions.'),t('Sin cifras verificadas del caso no se calcula un ROI para Campus Bikes.','Without verified case figures no Campus Bikes ROI is calculated.'),t('ROI no equivale a VAN ni demuestra por sí solo viabilidad global.','ROI is not NPV and does not by itself prove overall feasibility.'),['cost','benefit','npv','decision']);
  concept('npv','foundation',t('VAN · valor actual neto','NPV · net present value'),t('Valor presente de flujos futuros netos considerados, descontados según una tasa y supuestos explícitos.','Present value of considered future net cash flows discounted using an explicit rate and assumptions.'),t('Hace visible el efecto del tiempo sobre valores económicos esperados.','It makes the effect of time on expected monetary values visible.'),t('Necesita flujos, periodos y tasa sustentados antes de comparar alternativas.','It needs supported cash flows, periods, and rate before options can be compared.'),t('No se calcula VAN de Campus Bikes sin flujos ni tasa aportados.','No Campus Bikes NPV is calculated without supplied cash flows and discount rate.'),t('VAN no es ROI ni una promesa de resultado futuro.','NPV is neither ROI nor a promise of a future outcome.'),['cost','benefit','roi','decision']);
  concept('performance','foundation',t('Rendimiento','Performance'),t('Qué tan bien cumple una alternativa los resultados y condiciones que se hayan definido.','How well an option meets the outcomes and conditions that have been defined.'),t('Permite examinar desempeño más allá de una comparación monetaria.','It allows examination of performance beyond a monetary comparison.'),t('Se define qué se medirá y con qué evidencia antes de calificarlo.','What will be measured and with which evidence is defined before scoring it.'),t('Tiempo de respuesta sería una dimensión candidata, sin umbral numérico inventado.','Response time would be a candidate dimension, with no invented numeric threshold.'),t('No se confunde rendimiento técnico con ROI ni se atribuye un resultado medido al caso.','Technical performance is not ROI, and no measured outcome is attributed to the case.'),['criteria','evidence','roi']);
  concept('comparison','foundation',t('Comparación','Comparison'),t('Examen consistente de alternativas frente a los mismos criterios.','Consistent examination of alternatives against the same criteria.'),t('Permite reconocer ventajas, vacíos de evidencia y compensaciones entre opciones.','It exposes advantages, evidence gaps, and tradeoffs between options.'),t('Ordena evidencia, cifras y supuestos sin llenar huecos como si fueran hechos.','It organizes evidence, figures, and assumptions without filling gaps as facts.'),t('Campus Bikes puede contrastar rutas cuando existan datos comparables.','Campus Bikes can compare routes when comparable data exists.'),t('Una tabla bien organizada no sustituye datos ausentes.','A well-organized table does not replace missing data.'),['alternative','criteria','evidence','decision']);
  concept('decision','foundation',t('Decisión justificada','Reasoned decision'),t('Elección documentada de avanzar, reformular o detener la alternativa según evidencia y criterios.','A documented choice to proceed, reframe, or stop an option using evidence and criteria.'),t('Conecta el análisis con una responsabilidad de acción.','It connects analysis to responsibility for action.'),t('Registra la opción, sus razones, incertidumbres y responsable de aceptación.','It records the option, rationale, uncertainties, and person accountable for acceptance.'),t('La actividad didáctica no declara una estrategia ganadora para Campus Bikes.','The teaching activity does not declare a winning Campus Bikes strategy.'),t('La recomendación de IA no es una autorización humana.','An AI recommendation is not human authorization.'),['comparison','criteria','strategy']);

  const diagrams = [
    { id:'01',kind:'objects',title:t('Otra forma de mirar el sistema','Another way to see the system'),question:t('¿Qué cambia cuando observamos el sistema como objetos?','What changes when we view the system as objects?'),
      intro:t('Retomamos el mismo sistema de la Semana 3 y reconocemos entidades concretas, sus datos y su comportamiento.','We return to the same Week 3 system and identify concrete entities, their data, and behavior.'),
      case:t('Campus Bikes: una bicicleta concreta y la clase Bicicleta son una ilustración para aprender.','Campus Bikes: one concrete bicycle and the Bicycle class are a teaching illustration.'),
      metaphor:t('Como una ficha de un ejemplar y la descripción del tipo al que pertenece.','Like a record for one item and the description of the type it belongs to.'),
      ids:['object','instance','class','attribute','method'], discover:[t('Un objeto es concreto; una clase describe un tipo.','An object is concrete; a class describes a type.'),t('Los atributos describen estado.','Attributes describe state.'),t('Los métodos expresan comportamiento.','Methods express behavior.')],
      bridge:t('Si ya reconocemos objetos, ¿cómo colaboran para producir un resultado?','Now that we recognize objects, how do they collaborate to produce an outcome?'),
      links:[['r01a','instance','class',t('es parte del tipo','belongs to type'),t('La instancia sigue la estructura descrita por su clase.','The instance follows the structure described by its class.')],['r01b','class','attribute',t('define estado','defines state'),t('Los atributos describen datos compartidos como estructura, con valores propios por instancia.','Attributes describe a shared data structure with each instance holding its own values.')],['r01c','class','method',t('define comportamiento','defines behavior'),t('Los métodos expresan acciones que pueden solicitarse a los objetos de la clase.','Methods express actions that can be requested from class instances.')]],
      ai:[['object',t('Sugerir objetos candidatos','Suggest candidate objects'),t('La IA organiza nombres del dominio a partir de evidencia disponible.','AI organizes domain names from available evidence.'),t('Aparece un borrador para discutir, no un inventario confirmado.','A draft appears for discussion, not a confirmed inventory.'),t('El analista valida entidades y límites.','The analyst validates entities and boundaries.')],['method',t('Sugerir responsabilidades','Suggest responsibilities'),t('La IA propone operaciones candidatas vinculadas a una necesidad.','AI proposes candidate operations linked to a need.'),t('Se hacen visibles preguntas sobre comportamiento.','Questions about behavior become visible.'),t('El equipo confirma qué comportamiento pertenece a cada objeto.','The team confirms which behavior belongs to each object.')]] },
    { id:'02',kind:'collaboration',title:t('Objetos que colaboran','Objects that collaborate'),question:t('¿Cómo colaboran varios objetos para producir un resultado?','How do several objects collaborate to produce a result?'),
      intro:t('Cada objeto aporta una responsabilidad. Las solicitudes entre ellos ayudan a comprender cómo se alcanza un objetivo.','Each object contributes a responsibility. Requests between them help explain how a goal is achieved.'),
      case:t('Campus Bikes: una consulta ilustrativa solicita información y después comunica una respuesta.','Campus Bikes: an illustrative query asks for information and then communicates a response.'),
      metaphor:t('En un equipo, cada integrante responde por una parte del trabajo sin que todos deban conocer cada detalle interno.','In a team, each person owns part of the work without everyone needing every internal detail.'),
      ids:['responsibility','message','encapsulation','polymorphism'], discover:[t('Los objetos colaboran mediante responsabilidades y mensajes.','Objects collaborate through responsibilities and messages.'),t('La encapsulación delimita el acceso a sus detalles internos.','Encapsulation bounds access to internal details.'),t('El polimorfismo permite variantes justificadas de comportamiento.','Polymorphism permits justified behavioral variants.')],
      bridge:t('Podemos explicar esta colaboración. ¿Cómo la representamos con precisión y la compartimos?','We can explain this collaboration. How can we represent it precisely and share it?'),
      links:[['r02a','responsibility','message',t('se solicita mediante','is requested through'),t('Un mensaje pide a otro participante ejecutar una responsabilidad.','A message asks another participant to perform a responsibility.')],['r02b','message','encapsulation',t('respeta el límite interno','respects the internal boundary'),t('Solicitar una operación evita depender de detalles internos innecesarios.','Requesting an operation avoids dependence on unnecessary internal details.')]],
      ai:[['responsibility',t('Revisar duplicidades','Check overlap'),t('La IA señala responsabilidades repetidas como preguntas de análisis.','AI flags repeated responsibilities as analysis questions.'),t('Se explicita una posible duplicidad.','A possible overlap becomes explicit.'),t('El analista confirma si es real.','The analyst confirms whether it is real.')],['message',t('Proponer colaboraciones','Suggest collaborations'),t('La IA dibuja una posible secuencia de solicitudes.','AI sketches a possible sequence of requests.'),t('Surgen caminos candidatos que se pueden contrastar.','Candidate paths arise for comparison.'),t('No se aceptan mensajes sin respaldo del caso.','Messages without case support are not accepted.')]] },
    { id:'03',kind:'usecase',title:t('Los objetivos de quienes usan el sistema','The goals of those who use the system'),question:t('¿Quién interactúa con el sistema y qué necesita conseguir?','Who interacts with the system, and what do they need to achieve?'),
      intro:t('La necesidad de explicar la colaboración nos lleva a UML. Comenzamos por objetivos visibles para actores externos.','The need to explain collaboration leads us to UML. We start with goals visible to external actors.'),
      case:t('Campus Bikes: Cliente y Consultar disponibilidad forman un ejemplo didáctico; su alcance requiere contraste con el caso.','Campus Bikes: Customer and Check availability form a teaching example; scope must be checked against the case.'),
      metaphor:t('Un mapa de servicios dice quién puede solicitar un resultado sin describir aún todas las piezas internas.','A service map says who may request an outcome without yet describing every internal part.'),
      ids:['uml','actor','goal','usecase','boundary'], discover:[t('UML aparece para expresar preguntas que ya sabemos formular.','UML appears to express questions we already know how to ask.'),t('El actor persigue un objetivo desde fuera del sistema.','The actor seeks a goal from outside the system.'),t('Un caso de uso no equivale a una pantalla.','A use case is not a screen.')],
      bridge:t('Si sabemos qué objetivos deben atenderse, ¿qué estructura interna los soportaría?','If we know which goals must be met, what internal structure would support them?'),
      links:[['r03a','actor','usecase',t('persigue el objetivo','pursues the goal'),t('El actor participa en el caso de uso para alcanzar un resultado.','The actor participates in the use case to reach an outcome.')],['r03b','boundary','usecase',t('incluye capacidad','contains capability'),t('El límite ubica la capacidad modelada dentro del sistema.','The boundary locates the modeled capability inside the system.')]],
      ai:[['actor',t('Proponer actores candidatos','Suggest candidate actors'),t('La IA organiza roles mencionados en descripciones.','AI organizes roles mentioned in descriptions.'),t('Hace visibles participantes que deben confirmarse.','It exposes participants who must be confirmed.'),t('Usuarios y analista validan los roles.','Users and analyst validate the roles.')],['usecase',t('Agrupar objetivos','Group goals'),t('La IA propone casos de uso desde necesidades documentadas.','AI proposes use cases from documented needs.'),t('Aparecen posibles duplicados o ambigüedades.','Possible duplicates or ambiguities emerge.'),t('El interesado confirma objetivos y alcance.','The stakeholder confirms goals and scope.')]] },
    { id:'04',kind:'classes',title:t('La estructura que sostiene el sistema','The structure that supports the system'),question:t('¿Qué clases, responsabilidades y relaciones necesita el sistema?','Which classes, responsibilities, and links does the system need?'),
      intro:t('El diagrama de clases formaliza tipos, atributos, operaciones y vínculos para revisar una estructura candidata.','The class diagram formalizes types, attributes, operations, and links to review a candidate structure.'),
      case:t('Campus Bikes: Cliente, Consulta y Bicicleta son nombres ilustrativos del modelo, no clases aprobadas.','Campus Bikes: Customer, Query, and Bicycle are illustrative model names, not approved classes.'),
      metaphor:t('El plano de relaciones de un equipo muestra responsabilidades y dependencias, antes de escoger herramientas concretas.','A team relationship plan shows responsibilities and dependencies before choosing concrete tools.'),
      ids:['classdiagram','class','association','attribute','operation'], discover:[t('Una clase reúne datos y operaciones relacionados.','A class brings related data and operations together.'),t('Cada relación debe tener significado.','Each relationship needs a meaning.'),t('El diagrama de clases no equivale a una base de datos.','A class diagram is not a database.')],
      bridge:t('La estructura muestra quiénes pueden participar. ¿Cómo ocurre un escenario concreto a lo largo del tiempo?','The structure shows who can participate. How does a concrete scenario unfold over time?'),
      links:[['r04a','classdiagram','class',t('organiza tipos','organizes types'),t('El diagrama muestra clases y responsabilidades como una estructura.','The diagram shows classes and responsibilities as a structure.')],['r04b','class','association',t('mantiene relaciones','has relationships'),t('Una asociación explica qué vínculo del dominio se está modelando.','An association explains which domain link is being modeled.')],['r04c','class','operation',t('ofrece operaciones','offers operations'),t('Las operaciones ubican el comportamiento ofrecido por objetos de esa clase.','Operations locate behavior offered by instances of that class.')]],
      ai:[['classdiagram',t('Proponer estructura','Suggest structure'),t('La IA propone un borrador de clases apoyado en objetivos existentes.','AI drafts classes using existing goals.'),t('Se pueden comparar estructuras candidatas.','Candidate structures can be compared.'),t('El analista confirma significado y límites.','The analyst confirms meaning and boundaries.')],['association',t('Señalar vínculos dudosos','Flag doubtful links'),t('La IA pregunta por relaciones sin justificación suficiente.','AI questions relationships lacking sufficient support.'),t('Se hacen visibles supuestos de modelado.','Modeling assumptions become visible.'),t('El equipo acepta o corrige vínculos con evidencia.','The team accepts or corrects links using evidence.')]] },
    { id:'05',kind:'perspectives',title:t('Un escenario, tres perspectivas','One scenario, three perspectives'),question:t('¿Qué revela cada vista del comportamiento del mismo escenario?','What does each view reveal about the same scenario’s behavior?'),
      intro:t('La consulta didáctica de Campus Bikes no cambia. Solo alternamos la vista: secuencia, estados o actividad.','The Campus Bikes teaching query stays the same. Only the view changes: sequence, states, or activity.'),
      case:t('Escenario único ilustrativo: una persona solicita conocer disponibilidad, la consulta se revisa y se informa una respuesta.','One illustrative scenario: someone requests availability, the query is reviewed, and a response is reported.'),
      metaphor:t('Una escena puede observarse por el orden del diálogo, la situación de un personaje o las acciones realizadas.','A scene can be viewed through dialogue order, a character’s situation, or the actions performed.'),
      ids:['scenario','sequence','state','transition','activity','decisionpoint'], discover:[t('El escenario y sus participantes permanecen constantes.','The scenario and its participants stay constant.'),t('Secuencia explica mensajes; estados, cambios; actividad, trabajo.','Sequence explains messages; states, changes; activity, work.'),t('Las vistas deben ser compatibles entre sí.','The views must be compatible.')],
      bridge:t('Si ya entendemos ese comportamiento, ¿necesitamos construir software nuevo para ofrecerlo?','If we understand that behavior, do we need to build new software to provide it?'),
      links:[['r05a','scenario','sequence',t('se observa por mensajes','is seen through messages'),t('La vista secuencial ordena interacciones del mismo escenario.','The sequence view orders interactions of the same scenario.')],['r05b','scenario','state',t('se observa por cambios','is seen through changes'),t('La vista de estados sigue el ciclo de un objeto del mismo escenario.','The state view follows one object’s lifecycle in that scenario.')],['r05c','scenario','activity',t('se observa por acciones','is seen through actions'),t('La vista de actividad sigue las acciones del mismo escenario.','The activity view follows the actions of the same scenario.')]],
      ai:[['sequence',t('Comparar mensajes','Compare messages'),t('La IA contrasta participantes y solicitudes entre vistas.','AI compares participants and requests across views.'),t('Surgen diferencias que investigar.','Differences requiring investigation emerge.'),t('El analista confirma el escenario.','The analyst confirms the scenario.')],['transition',t('Señalar transiciones pendientes','Flag missing transitions'),t('La IA plantea preguntas sobre cambios de estado.','AI raises questions about state changes.'),t('Se revelan huecos candidatos.','Candidate gaps become visible.'),t('No se agregan reglas de negocio sin fuente.','No business rules are added without a source.')],['activity',t('Revisar caminos','Review paths'),t('La IA comprueba que el flujo representado no contradiga mensajes y estados.','AI checks whether the shown flow contradicts messages and states.'),t('Las vistas pueden compararse.','The views can be compared.'),t('El equipo valida comportamiento y excepciones.','The team validates behavior and exceptions.')]] },
    { id:'06',kind:'need',title:t('¿Realmente necesitamos desarrollar software?','Do we really need to build software?'),question:t('¿Qué necesidad debe resolverse y qué posibilidades existen?','What need must be met, and what possibilities exist?'),
      intro:t('Abrimos el espacio de soluciones antes de elegir una herramienta o proveedor. Ninguna ruta es ganadora todavía.','We open the solution space before choosing a tool or supplier. No route wins yet.'),
      case:t('Campus Bikes: la consulta didáctica permite explorar rutas; ninguna se presenta como decisión tomada.','Campus Bikes: the teaching query lets us explore routes; none is presented as a chosen decision.'),
      metaphor:t('Antes de construir una nueva carretera, observamos si basta cambiar el recorrido o usar una vía disponible.','Before building a new road, we check whether changing the route or using an existing road suffices.'),
      ids:['need','processchange','alternative','build','buy','web','outsourcing','offshoring'], discover:[t('Una necesidad no obliga a desarrollar software nuevo.','A need does not require new software.'),t('Se examinan proceso, herramientas y estrategias de obtención.','We examine process, tools, and acquisition strategies.'),t('Abrir opciones no significa elegir una.','Opening options does not mean choosing one.')],
      bridge:t('Si tenemos varias rutas candidatas, ¿qué cambia realmente entre ellas?','With several candidate routes, what actually differs between them?'),
      links:[['r06a','need','alternative',t('abre posibilidades','opens possibilities'),t('Una necesidad validada permite proponer alternativas apropiadas.','A validated need allows suitable alternatives to be proposed.')],['r06b','need','processchange',t('puede mejorar el proceso','may improve the process'),t('La necesidad también puede responder a un cambio de trabajo o coordinación.','The need may also be met by changing work or coordination.')]],
      ai:[['evidence',t('Ordenar evidencia','Organize evidence'),t('La IA agrupa datos disponibles y señala lagunas.','AI groups available data and flags gaps.'),t('Se ve qué está sustentado y qué requiere investigación.','What is supported or requires investigation becomes visible.'),t('El analista valida fuente y pertinencia.','The analyst validates source and relevance.')],['alternative',t('Sugerir alternativas candidatas','Suggest candidate alternatives'),t('La IA amplía la lista sin escoger una salida.','AI broadens the list without selecting an outcome.'),t('Aparecen rutas para estudiar, incluso sin IA.','Routes for study appear, including options without AI.'),t('Las personas deciden cuáles evaluar.','People decide which routes to assess.')]] },
    { id:'07',kind:'strategies',title:t('Estrategias para obtener la solución','Ways to obtain the solution'),question:t('¿Qué implica desarrollar, comprar o trabajar con un proveedor?','What follows from building, buying, or using a supplier?'),
      intro:t('Build y Buy indican cómo obtenemos capacidades; Web, cómo accedemos; outsourcing, quién trabaja; offshoring, dónde. Los ejes pueden combinarse.','Build and Buy concern how we obtain capabilities; Web, how we access them; outsourcing, who works; offshoring, where. These axes may combine.'),
      case:t('Campus Bikes compara rutas de manera didáctica; faltan datos para declarar la mejor opción.','Campus Bikes compares routes for learning; data is missing to declare the best option.'),
      metaphor:t('Elegir una comida, decidir quién la prepara y escoger dónde hacerlo son decisiones relacionadas, pero distintas.','Choosing a meal, who prepares it, and where are related but distinct decisions.'),
      ids:['strategy','build','buy','web','outsourcing','offshoring','ownership','location','control','risk'], discover:[t('Forma de obtención, canal, ejecutor y ubicación son ejes distintos.','Acquisition, channel, performer, and location are distinct axes.'),t('Una estrategia puede combinar varias elecciones.','A strategy may combine several choices.'),t('Cada ruta introduce compromisos que deben hacerse explícitos.','Each route brings commitments that must be made explicit.')],
      bridge:t('Ya entendemos las rutas. ¿Con qué evidencia justificamos cuál conviene?','We understand the routes. What evidence helps justify a suitable choice?'),
      links:[['r07a','strategy','ownership',t('define responsabilidades','defines responsibilities'),t('La estrategia deja claro quién controla cambios, entregables y obligaciones.','The strategy clarifies control of changes, deliverables, and obligations.')],['r07b','outsourcing','offshoring',t('pueden combinarse','can be combined'),t('Un proveedor puede trabajar en otro país; un equipo interno también.','A supplier may work abroad; so may an internal team.')],['r07c','strategy','control',t('modifica el control','changes control'),t('Cada ruta crea distintas dependencias y posibilidades de adaptación.','Each route creates different dependencies and room to adapt.')]],
      ai:[['strategy',t('Comparar criterios','Compare criteria'),t('La IA organiza condiciones conocidas de varias rutas.','AI organizes known conditions across routes.'),t('Los compromisos se pueden observar juntos.','Tradeoffs can be viewed together.'),t('La organización define prioridades.','The organization defines priorities.')],['risk',t('Señalar riesgos y supuestos','Flag risks and assumptions'),t('La IA destaca datos ausentes y dependencia de hipótesis.','AI highlights missing data and reliance on assumptions.'),t('La incertidumbre deja de estar oculta.','Uncertainty is no longer hidden.'),t('La dirección decide qué evidencia necesita.','Decision makers decide which evidence they need.')]] },
    { id:'08',kind:'decision',title:t('Una decisión sustentada en valor','A decision grounded in value'),question:t('¿Qué alternativa aporta valor suficiente bajo los supuestos disponibles?','Which option offers sufficient value under available assumptions?'),
      intro:t('Evidencia, criterios, alternativas, comparación y decisión forman una cadena. Sin cifras verificadas, ROI y VAN se explican sin calcular resultados del caso.','Evidence, criteria, options, comparison, and decision form a chain. Without verified figures, ROI and NPV are explained without calculating case results.'),
      case:t('Campus Bikes mantiene abiertas las alternativas hasta contar con costos, beneficios y supuestos sustentados.','Campus Bikes keeps options open until supported costs, benefits, and assumptions are available.'),
      metaphor:t('Una balanza solo ayuda si conocemos qué colocamos a cada lado y de dónde vienen las medidas.','A scale only helps if we know what is on each side and where the measures come from.'),
      ids:['evidence','criteria','alternative','comparison','decision','cost','benefit','roi','npv','performance'], discover:[t('La decisión se justifica con evidencia y criterios explícitos.','The decision rests on evidence and explicit criteria.'),t('ROI y VAN requieren supuestos y datos que no debemos inventar.','ROI and NPV need assumptions and data we must not invent.'),t('Las personas aceptan o rechazan los riesgos de la elección.','People accept or reject the risks of the choice.')],
      bridge:t('¿Cómo transformamos el modelo y la estrategia aceptados en un diseño concreto para las personas?','How do we turn the accepted model and strategy into a concrete design for people?'),
      links:[['r08a','evidence','criteria',t('sustenta criterios','supports criteria'),t('La evidencia explica por qué un criterio es relevante y cómo se medirá.','Evidence explains why a criterion matters and how it will be measured.')],['r08b','criteria','comparison',t('ordena la comparación','structures comparison'),t('Los mismos criterios permiten contrastar alternativas de forma consistente.','The same criteria allow consistent comparisons across options.')],['r08c','comparison','decision',t('fundamenta la decisión','grounds the decision'),t('La comparación muestra razones, incertidumbres y responsables antes de decidir.','The comparison shows reasons, uncertainties, and accountability before a decision.')]],
      ai:[['evidence',t('Organizar evidencia','Organize evidence'),t('La IA clasifica información y destaca su fuente o ausencia.','AI organizes information and highlights its source or absence.'),t('Se distinguen datos de supuestos.','Data can be distinguished from assumptions.'),t('El analista comprueba veracidad y pertinencia.','The analyst checks accuracy and relevance.')],['comparison',t('Explorar escenarios','Explore scenarios'),t('La IA muestra qué cambiaría con supuestos distintos.','AI shows what would change under different assumptions.'),t('Las decisiones se vuelven sensibles a supuestos visibles.','Decision sensitivity to visible assumptions becomes clear.'),t('Los datos y criterios son validados por personas.','People validate data and criteria.')],['decision',t('Explicar opciones','Explain options'),t('La IA resume razones y dudas sin aprobar una ruta.','AI summarizes reasons and doubts without approving a route.'),t('La discusión se vuelve más explícita.','The discussion becomes more explicit.'),t('La decisión y su responsabilidad siguen siendo humanas.','The decision and accountability remain human.')]] }
  ];

  diagrams.forEach(diagram => {
    diagram.baseLinks = diagram.links.map(row => relation(row[0], row[1], row[2], row[3], row[4], diagram.case));
    diagram.aiLinks = diagram.ai.map((row, index) => {
      const id = 'w4-ai-' + diagram.id + '-' + (index + 1);
      concept(id, 'ai', row[1], row[2],
        t('Hace explícito dónde entra IA y qué cambia en este diagrama.', 'It makes explicit where AI enters and what changes in this diagram.'),
        row[2], diagram.case,
        t('Una propuesta de IA no equivale a un modelo ni una decisión validados.', 'An AI proposal is not a validated model or decision.'), [row[0]]);
      db.concepts[id].ai = { connection: row[1], does: row[2], changes: row[3], validate: row[4] };
      return { id, to: row[0], action: row[1], does: row[2], changes: row[3], validate: row[4] };
    });
    diagram.ids = Array.from(new Set(diagram.ids));
  });
  db.diagrams = diagrams;
})();
