(() => {
  const B = (es, en) => ({ es, en });
  const SOURCE = {
    course_week: "Week 1",
    source_type: "Course material",
    source_title: "CST212 Week 1 learning materials",
    author: null,
    year: null,
    canonical_url: "https://tiffinglobal.myopenlms.net/course/view.php?id=24932",
    status: "SOURCE_METADATA_PENDING"
  };
  const domains = ["business", "education", "biology", "psychology", "music"];
  const domainNames = {
    business: B("Negocios", "Business"), education: B("Educación", "Education"),
    biology: B("Biología", "Biology"), psychology: B("Psicología", "Psychology"), music: B("Música", "Music")
  };
  const genericExamples = (es, en) => ({
    business: B(`En una organización, ${es.toLowerCase()} orienta cómo se coordina el trabajo.`, `In an organization, ${en.toLowerCase()} guides how work is coordinated.`),
    education: B(`En educación, ${es.toLowerCase()} ayuda a conectar personas, actividades y resultados.`, `In education, ${en.toLowerCase()} connects people, activities and outcomes.`),
    biology: B(`En biología, ${es.toLowerCase()} puede observarse como parte de un conjunto interdependiente.`, `In biology, ${en.toLowerCase()} can be observed as part of an interdependent whole.`),
    psychology: B(`En psicología, ${es.toLowerCase()} permite examinar relaciones entre conducta, contexto y resultados.`, `In psychology, ${en.toLowerCase()} helps examine relationships among behavior, context and outcomes.`),
    music: B(`En música, ${es.toLowerCase()} ayuda a coordinar interpretación, estructura y resultado.`, `In music, ${en.toLowerCase()} helps coordinate performance, structure and outcome.`)
  });
  const C = {};
  const D = (key, title, definition, why, question, metaphor, options = {}) => {
    C[key] = {
      key, title,
      short_definition: definition,
      why_it_matters: why,
      guiding_question: question,
      metaphor,
      examples: options.examples || genericExamples(title.es, title.en),
      related_concepts: options.related || [],
      not_to_confuse_with: options.confuse || B("Un concepto diferente dentro del análisis.", "A different concept within analysis."),
      academic_source: options.source || SOURCE,
      ai_lens: options.ai || B("La IA puede apoyar este trabajo, pero sus resultados requieren evidencia y validación humana.", "AI may support this work, but its outputs require evidence and human validation.")
    };
  };

  D("system", B("Sistema", "System"), B("Conjunto conectado de elementos que interactúan para lograr un propósito.", "A connected set of elements that interact to achieve a purpose."), B("Cambiar un elemento puede afectar muchos otros y modificar el resultado total.", "Changing one element can affect many others and alter the overall outcome."), B("¿Qué elementos y relaciones producen el resultado que observamos?", "Which elements and relationships produce the outcome we observe?"), B("Una orquesta: un instrumento no es la orquesta.", "An orchestra: one instrument is not the orchestra."), { related: ["people","processes","information","rules","resources","technology"], confuse: B("Software o una herramienta aislada.", "Software or an isolated tool."), examples: { business:B("Una empresa de reservas conecta clientes, empleados, reglas, disponibilidad, pagos, procedimientos y software.","A reservation company connects customers, staff, rules, availability, payments, procedures and software."), education:B("Una escuela conecta estudiantes, docentes, currículo, horarios, evaluación, políticas y herramientas digitales.","A school connects students, teachers, curriculum, schedules, assessment, policies and digital tools."), biology:B("El cuerpo conecta órganos, señales, recursos y mecanismos de regulación.","The body connects organs, signals, resources and regulation mechanisms."), psychology:B("Aprender conecta atención, memoria, emoción, contexto y retroalimentación.","Learning connects attention, memory, emotion, context and feedback."), music:B("Una orquesta conecta músicos, director, instrumentos, partitura y acústica.","An orchestra connects musicians, conductor, instruments, score and acoustics.") } });
  D("analyst", B("Analista de sistemas", "Systems analyst"), B("Profesional que conecta necesidades organizacionales con posibles soluciones de sistema.", "A professional who connects organizational needs with possible system solutions."), B("Evita que una petición tecnológica sustituya la comprensión del negocio.", "Prevents a technology request from replacing business understanding."), B("¿Qué necesita realmente la organización y cómo podría ayudar un sistema?", "What does the organization actually need, and how could a system help?"), B("Traductor entre el mundo del negocio y el mundo técnico.", "A translator between the business and technical worlds."), { related:["sdlc","planning","investigation"], confuse:B("Un programador que recibe una solución ya decidida.","A programmer receiving an already-decided solution."), ai:B("La IA puede resumir, buscar, comparar y detectar patrones; el analista conserva contexto, ética, juicio y responsabilidad.","AI can summarize, search, compare and detect patterns; the analyst retains context, ethics, judgment and accountability.") });
  D("sdlc", B("SDLC", "SDLC"), B("Marco estructurado para organizar el trabajo de crear o mejorar un sistema de información.", "A structured framework for organizing the work of creating or improving an information system."), B("Impide saltar directamente a la tecnología antes de comprender problema, requisitos y diseño.", "It prevents jumping directly to technology before understanding the problem, requirements and design."), B("¿En qué etapa del recorrido de desarrollo estamos?", "What stage of the system-development journey are we in?"), B("Construir una casa: comprender, planear, construir y mantener.", "Building a house: understand, plan, build and maintain."), { related:["planning","analyst"], confuse:B("El sistema que se está estudiando.","The system being studied.") });
  D("planning", B("Planeación", "Planning"), B("Primera fase del SDLC, donde se decide si existe una razón sólida para iniciar.", "The first SDLC phase, where we decide whether there is a strong reason to begin."), B("Protege a la organización de invertir en proyectos sin necesidad, alineación o viabilidad suficiente.", "It protects the organization from investing in projects without sufficient need, alignment or feasibility."), B("¿Debemos iniciar este proyecto?", "Should we start this project?"), B("La puerta de embarque antes de comenzar un viaje costoso.", "The boarding gate before beginning an expensive journey."), { related:["business_case","feasibility"], confuse:B("El cronograma detallado de ejecución.","The detailed delivery schedule.") });
  D("people", B("Personas", "People"), B("Quienes usan, operan, administran o reciben efectos del sistema.", "Those who use, operate, manage or are affected by the system."), B("Sus decisiones, capacidades y necesidades influyen directamente en el resultado.", "Their decisions, capabilities and needs directly influence the outcome."), B("¿Quién participa, decide o recibe los resultados?", "Who participates, decides or receives the outcomes?"), B("Los actores de una obra.", "The actors in a play."), { related:["system","processes","sociotechnical"] });
  D("processes", B("Procesos", "Processes"), B("Actividades relacionadas que transforman entradas en resultados.", "Related activities that transform inputs into outcomes."), B("Revelan cómo ocurre realmente el trabajo, más allá del organigrama o del software.", "They reveal how work actually happens beyond the org chart or software."), B("¿Qué trabajo ocurre y en qué secuencia?", "What work happens and in what sequence?"), B("La ruta que sigue el trabajo.", "The route that work follows."), { related:["business_process","information","rules"] });
  D("information", B("Información", "Information"), B("Datos interpretados y utilizados para operar o tomar decisiones.", "Data interpreted and used to operate or make decisions."), B("Permite coordinar actividades y mantener una comprensión compartida del estado del sistema.", "It coordinates activities and maintains a shared understanding of system state."), B("¿Qué debemos saber para actuar correctamente?", "What must we know to act correctly?"), B("La memoria compartida del sistema.", "The shared memory of the system."), { related:["system","processes","evidence"] });
  D("rules", B("Reglas", "Rules"), B("Condiciones que guían o restringen comportamiento y decisiones.", "Conditions that guide or constrain behavior and decisions."), B("Hacen que el sistema actúe de manera consistente y explicable.", "They make system behavior consistent and explainable."), B("¿Qué está permitido, requerido o prohibido?", "What is allowed, required or prohibited?"), B("Barandas de seguridad en una carretera.", "Guardrails on a road."), { related:["processes","sociotechnical"] });
  D("resources", B("Recursos", "Resources"), B("Medios humanos, físicos, financieros u organizacionales usados por el sistema.", "Human, physical, financial or organizational means used by the system."), B("Definen la capacidad real para producir resultados.", "They define the real capacity to produce outcomes."), B("¿Con qué medios cuenta el sistema?", "What means are available to the system?"), B("Los ingredientes y utensilios de una cocina.", "The ingredients and tools in a kitchen."), { related:["system","feasibility"] });
  D("technology", B("Tecnología", "Technology"), B("Herramientas técnicas que apoyan la operación del sistema.", "Technical tools that support system operation."), B("Puede aumentar capacidad y coordinación, pero no sustituye personas, procesos ni reglas.", "It can increase capacity and coordination but does not replace people, processes or rules."), B("¿Qué herramienta apoya el trabajo y con qué límites?", "Which tool supports the work, and within what limits?"), B("Un instrumento dentro de la orquesta.", "An instrument within the orchestra."), { related:["software","system"], confuse:B("El sistema completo.","The complete system."), ai:B("La IA puede ser un componente dentro de tecnología: IA ⊂ tecnología ⊂ sistema.","AI may be a component within technology: AI ⊂ technology ⊂ system.") });
  D("software", B("Software", "Software"), B("Programas e instrucciones digitales que ejecutan funciones específicas.", "Programs and digital instructions that perform specific functions."), B("Es una herramienta posible, no una descripción completa del sistema organizacional.", "It is a possible tool, not a complete description of the organizational system."), B("¿Qué función específica realiza este programa?", "What specific function does this program perform?"), B("Una aplicación de reservas dentro de toda la operación.", "A reservation application within the whole operation."), { related:["technology","system"], confuse:B("El sistema completo de reservas con personas, reglas, datos y operaciones.","The complete reservation system with people, rules, data and operations.") });
  D("sociotechnical", B("Sistema sociotécnico", "Sociotechnical system"), B("Sistema cuyo resultado depende de la interacción entre elementos sociales, organizacionales y técnicos.", "A system whose outcome depends on interaction among social, organizational and technical elements."), B("Una tecnología correcta no garantiza un sistema correcto si fallan adopción, reglas, cultura o responsabilidad.", "Correct technology does not guarantee a correct system when adoption, rules, culture or accountability fail."), B("¿Cómo se afectan mutuamente las personas, la organización y la tecnología?", "How do people, organization and technology affect one another?"), B("Un automóvil necesita vehículo, conductor, carretera y reglas de tránsito.", "A car needs the vehicle, driver, road and traffic rules."), { related:["people","technology","system_outcome"], confuse:B("Un sistema puramente técnico.","A purely technical system."), ai:B("Agregar IA cambia roles, capacidades, autoridad, confianza, cultura, decisiones y responsabilidad, no solo software.","Adding AI changes roles, capabilities, authority, trust, culture, decisions and accountability, not only software.") });
  D("system_outcome", B("Resultado del sistema", "System outcome"), B("Efecto producido por la interacción de los componentes del sistema.", "The effect produced by interaction among system components."), B("Permite evaluar el conjunto y no únicamente si una herramienta funciona.", "It evaluates the whole rather than only whether a tool works."), B("¿El sistema completo produce el resultado que necesitamos?", "Does the whole system produce the outcome we need?"), B("La música que produce toda la orquesta.", "The music produced by the whole orchestra."), { related:["sociotechnical","business_process"] });
  D("business_process", B("Proceso de negocio", "Business process"), B("Conjunto de actividades relacionadas que produce un resultado para la organización o el cliente.", "A set of related activities that produces an outcome for the organization or customer."), B("Permite entender el trabajo actual antes de cambiarlo o automatizarlo.", "It helps us understand current work before changing or automating it."), B("¿Qué ocurre desde que aparece una necesidad hasta que se produce el resultado?", "What happens from the moment a need appears until an outcome is produced?"), B("Una receta: ingredientes sin secuencia ni acciones no producen el plato.", "A recipe: ingredients without sequence and actions do not produce the dish."), { related:["process_modeling","processes","investigation"], confuse:B("Una lista aislada de tareas o una pantalla de software.","An isolated task list or software screen."), examples:{ business:B("Completar una reserva desde la solicitud hasta la confirmación.","Complete a reservation from request to confirmation."), education:B("Matricular a un estudiante desde la solicitud hasta su inscripción.","Enroll a student from application to registration."), biology:B("La digestión transforma alimento en nutrientes disponibles.","Digestion transforms food into available nutrients."), psychology:B("Un proceso de aprendizaje transforma experiencia y práctica en comprensión.","A learning process transforms experience and practice into understanding."), music:B("Un ensayo transforma partitura y práctica en interpretación coordinada.","A rehearsal transforms score and practice into coordinated performance.") }, ai:B("La IA puede clasificar entradas, recomendar, apoyar decisiones o monitorear; automatizar un proceso malo solo acelera sus fallas.","AI may classify inputs, recommend, support decisions or monitor; automating a bad process only accelerates its failures.") });
  D("process_modeling", B("Modelado de procesos", "Process modeling"), B("Representación visual de cómo se realiza el trabajo.", "A visual representation of how work is performed."), B("Hace visibles duplicación, espera, errores, pasos manuales, responsabilidades e oportunidades de mejora.", "It reveals duplication, waiting, errors, manual steps, responsibilities and improvement opportunities."), B("¿Cómo fluye el trabajo actual y dónde pierde valor?", "How does current work flow, and where does it lose value?"), B("El mapa de una ruta antes de intentar acortarla.", "A route map before trying to shorten it."), { related:["business_process","investigation"], confuse:B("El proceso real; el modelo es su representación.","The actual process; the model is its representation.") });
  D("object_view", B("Vista orientada a objetos", "Object-oriented view"), B("Forma de pensar sistemas mediante objetos que reúnen datos y comportamiento.", "A way of thinking about systems through objects that combine data and behavior."), B("Ayuda a reconocer entidades relevantes sin decidir todavía toda la implementación.", "It helps identify relevant entities without deciding the full implementation yet."), B("¿Qué entidad conserva estado y qué acciones realiza?", "Which entity holds state, and what actions does it perform?"), B("Una ficha que reúne identidad, características y acciones posibles.", "A profile that combines identity, characteristics and possible actions."), { related:["business_process","information"], confuse:B("Un modelo completo del proceso de negocio.","A complete business-process model.") });
  D("need", B("Necesidad u oportunidad", "Need or opportunity"), B("Brecha, aspiración u oportunidad de mejora que merece estudio.", "A gap, aspiration or improvement opportunity that deserves study."), B("Inicia la exploración sin asumir todavía la causa ni la solución.", "It begins exploration without assuming the cause or solution."), B("¿Qué resultado necesita mejorar y para quién?", "Which outcome needs improvement, and for whom?"), B("Una diferencia visible entre dónde estamos y dónde queremos estar.", "A visible gap between where we are and where we want to be."), { related:["signal","investigation"], confuse:B("Un problema tecnológico o una solución predeterminada.","A technology problem or predetermined solution.") });
  D("signal", B("Señal", "Signal"), B("Observación que indica que algo merece atención.", "An observation indicating that something deserves attention."), B("Activa preguntas, pero todavía no explica la causa.", "It triggers questions but does not yet explain the cause."), B("¿Qué cambió o se repite y merece investigación?", "What changed or repeats and deserves investigation?"), B("Una luz de advertencia en el tablero del automóvil.", "A warning light on a car dashboard."), { related:["symptom","investigation"], confuse:B("El diagnóstico confirmado.","The confirmed diagnosis."), examples:{ business:B("Aumentan las llamadas de clientes por reservas.","Customer calls about reservations increase."), education:B("La asistencia comienza a disminuir.","Attendance begins to decline."), biology:B("La temperatura corporal aumenta.","Body temperature rises."), psychology:B("El rendimiento empieza a disminuir.","Performance begins to decline."), music:B("La calidad de la interpretación baja.","Performance quality declines.") }, ai:B("La IA puede detectar tendencias o anomalías; una señal algorítmica sigue necesitando interpretación.","AI may detect trends or anomalies; an algorithmic signal still needs interpretation.") });
  D("symptom", B("Síntoma", "Symptom"), B("Efecto visible que puede apuntar a una causa más profunda.", "A visible effect that may point to a deeper cause."), B("Distinguir efecto de causa evita resolver superficialmente el problema.", "Distinguishing effect from cause prevents superficial problem solving."), B("¿Qué observamos y qué otras causas podrían explicarlo?", "What do we observe, and what other causes could explain it?"), B("La fiebre es un síntoma, no necesariamente la enfermedad.", "Fever is a symptom, not necessarily the disease."), { related:["signal","underlying_problem"], confuse:B("La causa raíz o problema subyacente.","The root cause or underlying problem."), examples:{ business:B("Aparecen reservas duplicadas.","Duplicate reservations appear."), education:B("Los estudiantes dejan de entregar actividades.","Students stop completing assignments."), biology:B("Se presenta fiebre.","Fever appears."), psychology:B("Aparece dificultad para concentrarse.","Difficulty concentrating appears."), music:B("Los músicos entran fuera de tiempo.","Musicians enter out of time.") } });
  D("investigation", B("Investigación preliminar", "Preliminary investigation"), B("Recopilación estructurada de hechos antes de concluir cuál es el problema.", "Structured fact-finding before concluding what the problem is."), B("Sustituye suposiciones por evidencia y permite reformular hipótesis.", "It replaces assumptions with evidence and enables hypothesis reframing."), B("¿Quién, qué, cuándo, dónde, cómo y por qué?", "Who, what, when, where, how and why?"), B("Trabajo detectivesco que contrasta pistas antes de acusar una causa.", "Detective work that compares clues before naming a cause."), { related:["evidence","underlying_problem","analyst"], confuse:B("Buscar únicamente datos que confirmen una idea inicial.","Looking only for data that confirms an initial idea."), ai:B("La IA puede analizar entrevistas, tickets, documentos, registros y datos históricos; las conclusiones requieren validación.","AI may analyze interviews, tickets, documents, logs and historical data; conclusions require validation.") });
  D("underlying_problem", B("Problema subyacente", "Underlying problem"), B("Condición respaldada por evidencia que explica efectos negativos relevantes.", "An evidence-supported condition that explains meaningful negative effects."), B("Permite actuar sobre causas y no solo aliviar síntomas.", "It enables action on causes rather than merely relieving symptoms."), B("¿Qué condición explica consistentemente la evidencia observada?", "Which condition consistently explains the observed evidence?"), B("La raíz bajo tierra que explica varias hojas marchitas.", "The root underground that explains several wilted leaves."), { related:["symptom","evidence","alternatives"], confuse:B("“Necesitamos una aplicación”; eso es una solución propuesta.","“We need an app”; that is a proposed solution."), examples:{ business:B("La disponibilidad se registra en varios lugares sin una fuente única actualizada.","Availability is recorded in several places without one current source of truth."), education:B("Debe investigarse si influyen acceso, pedagogía o carga de trabajo.","We must investigate whether access, pedagogy or workload are involved."), biology:B("Una infección u otra causa puede explicar la fiebre.","An infection or another cause may explain the fever."), psychology:B("La concentración reducida puede tener múltiples causas que requieren evaluación.","Reduced concentration may have multiple causes requiring assessment."), music:B("Tempo, monitoreo, ensayo o dirección pueden explicar la descoordinación.","Tempo, monitoring, rehearsal or direction may explain poor coordination.") }, ai:B("La IA puede proponer causas candidatas. Propuesta de IA ≠ diagnóstico aceptado.","AI may propose candidate causes. AI proposal ≠ accepted diagnosis.") });
  D("alternatives", B("Alternativas", "Alternatives"), B("Opciones distintas para responder al problema comprendido.", "Different options for responding to the understood problem."), B("Compararlas evita convertir la primera idea en una decisión automática.", "Comparing them prevents the first idea from becoming an automatic decision."), B("¿Qué combinaciones de proceso, personas, reglas o tecnología podrían funcionar?", "Which combinations of process, people, rules or technology could work?"), B("Varias rutas posibles hacia el mismo destino.", "Several possible routes to the same destination."), { related:["underlying_problem","feasibility","decision"], confuse:B("Una lista limitada únicamente a productos de software.","A list limited only to software products."), ai:B("La IA puede generar opciones; no debe convertir AI en la opción predeterminada.","AI may generate options; it must not make AI the default option.") });
  D("evidence", B("Evidencia", "Evidence"), B("Información confiable que confirma, contradice o reformula una interpretación.", "Reliable information that confirms, contradicts or reframes an interpretation."), B("Conecta afirmaciones con hechos y permite regresar a revisar el problema.", "It connects claims with facts and allows returning to review the problem."), B("¿Qué dato podría demostrar que nuestra interpretación es incorrecta?", "What evidence could show that our interpretation is wrong?"), B("La brújula del análisis.", "The compass of analysis."), { related:["investigation","decision","business_case"], confuse:B("Opinión, intuición o volumen de información sin calidad.","Opinion, intuition or information volume without quality."), ai:B("La IA puede comparar hipótesis con datos, pero la procedencia y calidad de la evidencia deben auditarse.","AI may compare hypotheses with data, but evidence provenance and quality must be audited.") });
  D("decision", B("Decisión", "Decision"), B("Elección razonada basada en lo aprendido.", "A reasoned choice based on what has been learned."), B("Convierte análisis en acción responsable, investigación adicional, reformulación o cierre.", "It turns analysis into responsible action, more investigation, reframing or closure."), B("¿Qué opción está mejor sustentada y quién asume responsabilidad?", "Which option is best supported, and who is accountable?"), B("Un cruce de caminos con señales y un responsable al volante.", "A crossroads with signs and an accountable driver."), { related:["evidence","go","reframe","stop"], confuse:B("Una recomendación automática sin autoridad definida.","An automated recommendation without defined authority."), ai:B("La IA puede preparar escenarios y recomendaciones; la aceptación requiere evidencia, gobernanza y autoridad humana.","AI may prepare scenarios and recommendations; acceptance requires evidence, governance and human authority.") });
  D("boundary", B("Límite del sistema", "System boundary"), B("Definición de qué queda dentro del alcance del análisis y qué permanece externo.", "A definition of what lies inside the analysis scope and what remains external."), B("Aclara responsabilidades, interfaces y supuestos.", "It clarifies responsibilities, interfaces and assumptions."), B("¿Dónde termina el sistema que estamos analizando?", "Where does the system we are analyzing end?"), B("Una casa separa interior y exterior, aunque tenga puertas e intercambios.", "A house separates inside and outside while still having doors and exchanges."), { related:["system","business_process"], confuse:B("Una barrera sin interacciones externas.","A barrier with no external interactions."), examples:{ business:B("Sistema de reservas frente al banco externo que procesa pagos.","Reservation system versus the external bank processing payments."), education:B("LMS frente al sistema externo de pago de matrícula.","LMS versus the external tuition-payment system."), biology:B("La membrana celular separa interior y exterior con intercambio controlado.","The cell membrane separates inside and outside with controlled exchange."), psychology:B("Un modelo cognitivo delimita variables dentro de su alcance explicativo.","A cognitive model defines variables inside its explanatory scope."), music:B("La banda integra el sistema de interpretación; la audiencia puede permanecer externa.","The band belongs to the performance system; the audience may remain external.") } });
  D("business_case", B("Caso de negocio", "Business case"), B("Argumento respaldado por evidencia que explica por qué un proyecto merece inversión.", "An evidence-based argument explaining why a project deserves investment."), B("Integra problema, beneficios, alternativas, costos, riesgos y alineación estratégica.", "It integrates the problem, benefits, alternatives, costs, risks and strategic alignment."), B("¿Por qué debería la organización invertir tiempo y dinero?", "Why should the organization invest time and money?"), B("El expediente que sustenta una decisión de inversión.", "The case file supporting an investment decision."), { related:["evidence","feasibility","planning"], confuse:B("Una presentación persuasiva sin evidencia.","A persuasive presentation without evidence.") });
  D("feasibility", B("Viabilidad", "Feasibility"), B("Evaluación de si una alternativa puede funcionar, aportar valor y entregarse responsablemente.", "An assessment of whether an alternative can work, create value and be delivered responsibly."), B("Evita confundir una idea atractiva con una inversión justificable.", "It prevents confusing an attractive idea with a justified investment."), B("¿Podemos hacerlo, funcionará, vale la pena y llegaremos a tiempo?", "Can we do it, will it work, is it worthwhile and can we arrive on time?"), B("Cuatro pruebas antes de cruzar un puente.", "Four checks before crossing a bridge."), { related:["operational","economic","technical","schedule"] });
  D("operational", B("Viabilidad operativa", "Operational feasibility"), B("Evalúa si la alternativa funcionará en las operaciones reales.", "Assesses whether the alternative will work in real operations."), B("Considera usuarios, procesos, adopción e impacto organizacional.", "It considers users, processes, adoption and organizational impact."), B("¿Funciona en la vida real?", "Does it work in real life?"), B("Probar si un zapato sirve al caminar, no solo en la vitrina.", "Testing whether a shoe works while walking, not only in a display."), { related:["feasibility","people","processes"] });
  D("economic", B("Viabilidad económica", "Economic feasibility"), B("Evalúa si los beneficios esperados justifican los costos.", "Assesses whether expected benefits justify the costs."), B("Compara inversión, operación, ahorro, riesgo y valor esperado.", "It compares investment, operation, savings, risk and expected value."), B("¿Vale la pena?", "Is it worth it?"), B("Una balanza entre valor esperado y recursos comprometidos.", "A scale balancing expected value and committed resources."), { related:["feasibility","business_case"], ai:B("La IA puede simular casos mejor, esperado y peor; una simulación depende de sus supuestos.","AI may simulate best, expected and worst cases; a simulation depends on its assumptions.") });
  D("technical", B("Viabilidad técnica", "Technical feasibility"), B("Evalúa si existen o pueden obtenerse capacidades, infraestructura, tecnología, habilidades y datos.", "Assesses whether capabilities, infrastructure, technology, skills and data exist or can be obtained."), B("Identifica dependencias y límites antes de prometer una solución.", "It identifies dependencies and limits before promising a solution."), B("¿Podemos hacerlo?", "Can we do it?"), B("Confirmar herramientas y materiales antes de construir.", "Confirming tools and materials before building."), { related:["feasibility","technology"], ai:B("La IA puede analizar arquitectura, repositorios, APIs, dependencias y datos; sus hallazgos deben verificarse.","AI may analyze architecture, repositories, APIs, dependencies and data; its findings must be verified.") });
  D("schedule", B("Viabilidad de cronograma", "Schedule feasibility"), B("Evalúa si el proyecto puede completarse en un tiempo aceptable.", "Assesses whether the project can be completed within an acceptable time."), B("Conecta alcance, dependencias, capacidad y riesgo de demora.", "It connects scope, dependencies, capacity and delay risk."), B("¿Podemos llegar a tiempo?", "Can we arrive on time?"), B("Planear una ruta con distancia, tráfico y hora de llegada.", "Planning a route with distance, traffic and arrival time."), { related:["feasibility","planning"], confuse:B("Programación de software.","Software programming."), ai:B("La IA puede identificar complejidad, dependencias y riesgo de retraso. Estimación de IA ≠ garantía.","AI may identify complexity, dependencies and delay risk. AI estimate ≠ guarantee.") });
  D("go", B("Avanzar", "Go"), B("La evidencia respalda continuar con el proyecto.", "Evidence supports proceeding with the project."), B("Convierte una oportunidad sustentada en compromiso de acción.", "It turns a supported opportunity into commitment to action."), B("¿Qué evidencia y condiciones autorizan avanzar?", "What evidence and conditions authorize proceeding?"), B("Luz verde después de comprobar el camino.", "A green light after checking the road."), { related:["decision","business_case"] });
  D("reframe", B("Reformular", "Reframe"), B("Existe valor potencial, pero deben revisarse supuestos, alcance o alternativas.", "Potential value remains, but assumptions, scope or alternatives must be revised."), B("Conserva el aprendizaje sin forzar una propuesta débil.", "It preserves learning without forcing a weak proposal."), B("¿Qué debemos comprender o cambiar antes de decidir otra vez?", "What must we understand or change before deciding again?"), B("Redibujar la ruta cuando el mapa no coincide con el terreno.", "Redrawing the route when the map does not match the terrain."), { related:["decision","investigation","alternatives"] });
  D("stop", B("Detener", "Stop"), B("La evidencia no justifica continuar con el proyecto actual.", "Evidence does not justify proceeding with the current project."), B("Puede prevenir una mala inversión; no significa que el análisis fracasó.", "It may prevent a bad investment; it does not mean analysis failed."), B("¿Qué costo o riesgo evitamos al detenernos?", "What cost or risk do we avoid by stopping?"), B("Cancelar un viaje cuando el puente no es seguro.", "Canceling a trip when the bridge is unsafe."), { related:["decision","feasibility"], confuse:B("Fracaso del análisis.","Failure of analysis.") });
  D("systems_planning", B("Planeación de sistemas", "Systems planning"), B("Disciplina que comprende el sistema, investiga la necesidad y decide con evidencia si debe comenzar un proyecto.", "The discipline of understanding the system, investigating the need and deciding with evidence whether a project should begin."), B("Une todos los aprendizajes de la Semana 1 en una decisión responsable.", "It unites all Week 1 learning in a responsible decision."), B("¿Qué debemos comprender y comprobar antes de actuar?", "What must we understand and prove before acting?"), B("La torre de control antes de autorizar el despegue.", "The control tower before authorizing takeoff."), { related:["system","investigation","business_case","feasibility"] });
  D("ai_assistance", B("Asistencia de IA", "AI assistance"), B("Uso opcional de IA para apoyar tareas de análisis delimitadas.", "Optional use of AI to support bounded analysis tasks."), B("Puede ampliar capacidad sin reemplazar contexto, evidencia, gobernanza ni responsabilidad.", "It can expand capacity without replacing context, evidence, governance or accountability."), B("¿Qué tarea puede apoyar la IA y quién valida el resultado?", "Which task can AI support, and who validates the output?"), B("Un copiloto que propone, mientras el responsable conserva el control.", "A copilot that proposes while the accountable person retains control."), { related:["analyst","evidence","human_gate"], confuse:B("Una decisión autónoma aceptada como verdad.","An autonomous decision accepted as truth."), ai:B("La IA genera candidatos; evidencia y gobernanza los convierten en decisiones aceptadas.","AI generates candidates; evidence and governance turn them into accepted decisions.") });
  D("ai_suitability", B("Idoneidad para IA", "AI suitability"), B("Revisión opcional de si una alternativa realmente se beneficia del uso de IA.", "An optional review of whether an alternative truly benefits from AI."), B("Evita introducir incertidumbre, costo o riesgo cuando otra solución sería mejor.", "It avoids adding uncertainty, cost or risk when another solution would be better."), B("¿Hay datos adecuados, tolerancia al error, valor y control humano suficiente?", "Are data, error tolerance, value and human control sufficient?"), B("Comprobar si una herramienta especializada corresponde al trabajo.", "Checking whether a specialized tool fits the job."), { related:["technical","operational","human_gate"], confuse:B("Una quinta dimensión canónica de viabilidad CST212.","A fifth canonical CST212 feasibility dimension."), ai:B("AI-FIRST EXTENSION. No es conocimiento canónico de CST212.","AI-FIRST EXTENSION. It is not canonical CST212 knowledge.") });
  D("human_gate", B("Validación humana", "Human gate"), B("Punto donde una persona autorizada revisa evidencia, riesgo y responsabilidad antes de aceptar un resultado.", "A point where an authorized person reviews evidence, risk and accountability before accepting an output."), B("Mantiene autoridad y rendición de cuentas cuando interviene IA.", "It preserves authority and accountability when AI is involved."), B("¿Quién puede aceptar, rechazar o pedir más evidencia?", "Who can accept, reject or request more evidence?"), B("La firma responsable antes de ejecutar una decisión.", "The accountable signature before executing a decision."), { related:["decision","ai_assistance","evidence"] });

  const isEn = () => document.documentElement.lang.toLowerCase().startsWith("en");
  const T = value => value?.[isEn() ? "en" : "es"] || "";
  const N = (key, label, cls = "") => `<button type="button" class="w1f-node ${cls}" data-w1f-key="${key}">${label || T(C[key].title)}</button>`;
  const Chip = (text, cls = "") => `<span class="w1f-chip ${cls}">${text}</span>`;
  const Arrow = () => `<span class="w1f-arrow" aria-hidden="true">↓</span>`;
  const AI = (key, label, roles) => `<button type="button" class="w1f-ai-node" data-w1f-key="${key}"><span>${label}</span><small>${roles}</small></button>`;
  const sourceLine = () => `<span class="w1f-source"><b>${isEn()?"SOURCE":"FUENTE"}</b> ${SOURCE.source_title} · ${SOURCE.status}</span>`;
  let aiOn = false;

  const diagramData = () => {
    const en = isEn();
    return [
      {
        title: en ? "Where are we? SDLC + Systems analyst" : "¿Dónde estamos? SDLC + analista de sistemas",
        caption: en ? "Week 1 begins in Planning: prove there is a strong enough reason to begin." : "La Semana 1 comienza en Planeación: comprobar que existe una razón suficientemente sólida para comenzar.",
        cls: "w1f-d1",
        html: `<p class="w1f-intro">${en?"Systems analysis and design understands the organization, its needs and processes before deciding how a system should improve.":"El análisis y diseño de sistemas comprende la organización, sus necesidades y procesos antes de decidir cómo mejorar un sistema."}</p><div class="w1f-vertical">${N("system")}${Arrow()}${N("analyst")}${Arrow()}${N("sdlc")}${Arrow()}<div class="w1f-phases">${N("planning", en?"PLANNING":"PLANEACIÓN", "is-focus")}${Chip(en?"ANALYSIS":"ANÁLISIS")}${Chip(en?"DESIGN":"DISEÑO")}${Chip(en?"IMPLEMENTATION":"IMPLEMENTACIÓN")}${Chip(en?"SUPPORT & SECURITY":"SOPORTE Y SEGURIDAD")}</div></div><div class="w1f-ai-layer">${AI("ai_assistance", en?"AI AUGMENTS THE ANALYST":"LA IA AUMENTA AL ANALISTA", "ASSIST · AUGMENT · HUMAN GATE")}<div class="w1f-dual"><span>${en?"HUMAN: context · judgment · ethics · accountability":"HUMANO: contexto · juicio · ética · responsabilidad"}</span><span>${en?"AI: summarize · search · detect · compare · draft":"IA: resumir · buscar · detectar · comparar · redactar"}</span></div></div>`
      },
      {
        title: en ? "What is a system?" : "¿Qué es un sistema?",
        caption: en ? "The system is the connected whole." : "El sistema es el conjunto conectado.",
        cls: "w1f-d2",
        html: `<div class="w1f-orbit">${N("system", null, "w1f-core")}${N("people",null,"p1")}${N("processes",null,"p2")}${N("information",null,"p3")}${N("rules",null,"p4")}${N("resources",null,"p5")}${N("technology",null,"p6")}</div><div class="w1f-ai-layer">${AI("ai_assistance", en?"AI COMPONENT":"COMPONENTE IA", "ASSIST")}<p>AI ⊂ ${en?"TECHNOLOGY":"TECNOLOGÍA"} ⊂ ${en?"SYSTEM":"SISTEMA"}</p></div>`
      },
      {
        title: en ? "System ≠ software + Sociotechnical system" : "Sistema ≠ software + sistema sociotécnico",
        caption: en ? "Technical success does not necessarily mean system success." : "El éxito técnico no significa necesariamente éxito del sistema.",
        cls: "w1f-d3",
        html: `<div class="w1f-containment"><b>${en?"SYSTEM CONTAINS":"EL SISTEMA CONTIENE"}</b><div>${Chip(en?"People":"Personas")}${Chip(en?"Processes":"Procesos")}${Chip(en?"Information":"Información")}${Chip(en?"Rules":"Reglas")}${Chip(en?"Resources":"Recursos")}<span class="w1f-tech-contain">${N("technology")}<span>${N("software")}<small>WEB APP · MOBILE APP · PORTAL · API</small></span></span></div></div><div class="w1f-socio"><div><b>${en?"SOCIAL":"SOCIAL"}</b>${Chip(en?"People · Roles · Culture · Policies · Rules":"Personas · Roles · Cultura · Políticas · Reglas")}</div>${N("sociotechnical", en?"SYSTEM OUTCOME":"RESULTADO DEL SISTEMA", "w1f-core")}<div><b>${en?"TECHNICAL":"TÉCNICO"}</b>${Chip(en?"Software · Hardware · Data · Infrastructure":"Software · Hardware · Datos · Infraestructura")}</div></div><div class="w1f-ai-layer">${AI("ai_assistance", en?"ADDING AI CHANGES BOTH SIDES":"AGREGAR IA CAMBIA AMBOS LADOS", "AUGMENT · HUMAN GATE")}</div>`
      },
      {
        title: en ? "How does the business work?" : "¿Cómo funciona el negocio?",
        caption: en ? "If we do not understand the current process, we may automate a bad process." : "Si no comprendemos el proceso actual, podemos automatizar un mal proceso.",
        cls: "w1f-d4",
        html: `<p class="w1f-intro">${en?"Before improving a system, understand how work is currently performed.":"Antes de mejorar un sistema, debemos comprender cómo se realiza actualmente el trabajo."}</p>${N("business_process", null, "w1f-process-title")}<div class="w1f-process-flow">${Chip(en?"INPUT":"ENTRADA")}${Arrow()}${Chip(en?"ACTIVITY":"ACTIVIDAD")}${Arrow()}${Chip(en?"DECISION":"DECISIÓN")}${Arrow()}${Chip(en?"ACTIVITY":"ACTIVIDAD")}${Arrow()}${Chip(en?"OUTPUT":"SALIDA")}</div><div class="w1f-influences">${Chip(en?"PEOPLE":"PERSONAS")}${Chip(en?"RULES":"REGLAS")}${Chip(en?"INFORMATION":"INFORMACIÓN")}${Chip(en?"RESOURCES":"RECURSOS")}${Chip(en?"TECHNOLOGY":"TECNOLOGÍA")}</div><div class="w1f-secondary">${N("process_modeling")}${N("object_view")}</div><div class="w1f-ai-layer"><div class="w1f-process-ai">${Chip(en?"AI CLASSIFICATION":"CLASIFICACIÓN IA","assist")}${Chip(en?"AI RECOMMENDATION":"RECOMENDACIÓN IA","augment")}${Chip(en?"HUMAN DECISION":"DECISIÓN HUMANA","human")}${Chip(en?"AI MONITORING":"MONITOREO IA","automate")}</div>${AI("ai_assistance", en?"EXAMPLE INTERVENTION POINTS":"PUNTOS DE INTERVENCIÓN DE EJEMPLO", "ASSIST · AUGMENT · AUTOMATE · HUMAN GATE")}</div>`
      },
      {
        title: en ? "From signal to underlying problem" : "De la señal al problema subyacente",
        caption: en ? "The process is not strictly linear: evidence can send us backward." : "El proceso no es estrictamente lineal: la evidencia puede devolvernos a pasos anteriores.",
        cls: "w1f-d5",
        html: `<div class="w1f-problem-flow">${N("need")}${Arrow()}${N("signal")}${Arrow()}${N("symptom")}${Arrow()}${N("investigation")}${Arrow()}${N("underlying_problem")}${Arrow()}${N("alternatives")}${Arrow()}${N("evidence")}${Arrow()}${N("decision")}<span class="w1f-feedback">↶ ${en?"EVIDENCE REFRAMES":"LA EVIDENCIA REFORMULA"}</span></div><div class="w1f-alternatives"><b>${en?"A PROBLEM DOES NOT AUTOMATICALLY REQUIRE SOFTWARE":"UN PROBLEMA NO REQUIERE SOFTWARE AUTOMÁTICAMENTE"}</b>${Chip(en?"PROCESS CHANGE":"CAMBIO DE PROCESO")}${Chip(en?"TRAINING / PEOPLE":"CAPACITACIÓN / PERSONAS")}${Chip(en?"POLICY CHANGE":"CAMBIO DE POLÍTICA")}${Chip(en?"INTEGRATION":"INTEGRACIÓN")}${Chip("SOFTWARE")}${Chip(en?"AUTOMATION":"AUTOMATIZACIÓN")}${Chip("AI")}${Chip(en?"NO TECHNOLOGY CHANGE":"SIN CAMBIO TECNOLÓGICO")}</div><div class="w1f-ai-layer"><div class="w1f-ai-chain"><span>${en?"SIGNAL":"SEÑAL"}</span>→<span>${en?"PATTERN DETECTION":"DETECCIÓN DE PATRONES"}</span>→<span>${en?"CANDIDATE CAUSES":"CAUSAS CANDIDATAS"}</span>→<span>${en?"HUMAN VALIDATION":"VALIDACIÓN HUMANA"}</span></div>${AI("human_gate", en?"AI PROPOSAL ≠ ACCEPTED DIAGNOSIS":"PROPUESTA IA ≠ DIAGNÓSTICO ACEPTADO", "AUGMENT · HUMAN GATE")}</div>`
      },
      {
        title: en ? "Business case + Feasibility" : "Caso de negocio + viabilidad",
        caption: en ? "GO, REFRAME and STOP are all valid analytical outcomes." : "AVANZAR, REFORMULAR y DETENER son resultados analíticos válidos.",
        cls: "w1f-d6",
        html: `<div class="w1f-feasibility">${N("business_case",null,"w1f-core")}${N("operational",null,"f1")}${N("economic",null,"f2")}${N("technical",null,"f3")}${N("schedule",null,"f4")}</div><p class="w1f-big-question">${en?"SHOULD THE ORGANIZATION INVEST?":"¿DEBERÍA INVERTIR LA ORGANIZACIÓN?"}</p><div class="w1f-outcomes">${N("go")}${N("reframe")}${N("stop")}</div><div class="w1f-ai-layer"><div class="w1f-ai-cases"><span>BEST CASE</span><span>EXPECTED CASE</span><span>WORST CASE</span></div>${AI("ai_suitability", en?"AI SUITABILITY · OPTIONAL OUTER LAYER":"IDONEIDAD PARA IA · CAPA EXTERNA OPCIONAL", "AI-FIRST EXTENSION · HUMAN GATE")}</div>`
      },
      {
        title: en ? "Week 1 consolidated model" : "Modelo consolidado de Semana 1",
        caption: en ? "Understand the system, investigate the need, decide with evidence whether a project should begin." : "Comprender el sistema, investigar la necesidad y decidir con evidencia si debe comenzar un proyecto.",
        cls: "w1f-d7",
        html: `<div class="w1f-ecosystem"><div class="w1f-ring ring1"><b>${en?"WHAT ARE WE ANALYZING?":"¿QUÉ ESTAMOS ANALIZANDO?"}</b>${N("system")}${N("sociotechnical")}${N("boundary")}</div><div class="w1f-ring ring2"><b>${en?"WHAT IS ACTUALLY HAPPENING?":"¿QUÉ ESTÁ OCURRIENDO REALMENTE?"}</b>${N("need")}${N("signal")}${N("symptom")}${N("investigation")}${N("underlying_problem")}</div><div class="w1f-ring ring3"><b>${en?"WHAT SHOULD WE DO?":"¿QUÉ DEBEMOS HACER?"}</b>${N("alternatives")}${N("business_case")}${N("feasibility")}<span>${N("go")}${N("reframe")}${N("stop")}</span></div>${N("systems_planning",null,"w1f-core")}</div><div class="w1f-ai-layer w1f-ai-ring"><b>${en?"AI ASSISTANCE LAYER":"CAPA DE ASISTENCIA IA"}</b><p>OBSERVE · DETECT · SUMMARIZE · MODEL · COMPARE · SIMULATE · RECOMMEND · MONITOR</p>${AI("ai_assistance", en?"AI AUGMENTS SYSTEMS PLANNING":"LA IA AUMENTA LA PLANEACIÓN DE SISTEMAS", "ASSIST · AUGMENT · AUTOMATE · HUMAN GATE")}</div>`
      }
    ];
  };

  const quizzes = () => isEn() ? [
    ["A reservation mobile app is:",["The entire system","A possible component of the system"],1,"Software can support the system, but the system also includes people, process, information, rules and resources."],
    ["Many duplicate reservations automatically reveal the root cause.",["True","False"],1,"They are a symptom. Investigation and evidence are needed to determine the underlying problem."],
    ["Which feasibility question asks whether benefits justify costs?",["Technical","Economic","Operational"],1,"Economic feasibility compares expected value with investment and operating costs."],
    ["STOP always means the analysis failed.",["True","False"],1,"A justified STOP can prevent a bad investment, which is a valuable analysis outcome."]
  ] : [
    ["Una aplicación móvil de reservas es:",["Todo el sistema","Un posible componente del sistema"],1,"El software puede apoyar el sistema, pero este también incluye personas, procesos, información, reglas y recursos."],
    ["Muchas reservas duplicadas revelan automáticamente la causa raíz.",["Verdadero","Falso"],1,"Son un síntoma. Se necesitan investigación y evidencia para determinar el problema subyacente."],
    ["¿Qué viabilidad pregunta si los beneficios justifican los costos?",["Técnica","Económica","Operativa"],1,"La viabilidad económica compara el valor esperado con la inversión y los costos de operación."],
    ["DETENER siempre significa que el análisis fracasó.",["Verdadero","Falso"],1,"Un DETENER justificado puede prevenir una mala inversión, lo cual es un resultado valioso del análisis."]
  ];

  const renderChecks = root => {
    root.querySelector(".w1f-learning-check")?.remove();
    const section = document.createElement("section");
    section.className = "w1f-learning-check";
    section.innerHTML = `<header><small>${isEn()?"MINI LEARNING CHECK":"MINI COMPROBACIÓN DE APRENDIZAJE"}</small><h3>${isEn()?"Can you distinguish the core ideas?":"¿Puedes distinguir las ideas centrales?"}</h3><p>${isEn()?"Answer and receive immediate explanation. No grades.":"Responde y recibe una explicación inmediata. Sin calificaciones."}</p></header><div class="w1f-quiz-list">${quizzes().map((q,i)=>`<article class="w1f-quiz" data-quiz="${i}" data-answer="${q[2]}"><b>${String(i+1).padStart(2,"0")}</b><p>${q[0]}</p><div>${q[1].map((a,j)=>`<button type="button" data-w1f-answer="${j}">${a}</button>`).join("")}</div><output></output></article>`).join("")}</div>`;
    root.appendChild(section);
  };

  const renderWeek = () => {
    const root = document.querySelector("#week-1");
    if (!root || root.dataset.week1Final === (isEn()?"en":"es")) return;
    root.dataset.week1Final = isEn()?"en":"es";
    root.classList.add("week1-final");
    const intro = root.querySelector(".week-intro");
    if (intro) {
      const question = intro.querySelector(".week-question");
      const copy = intro.querySelector(".week-copy");
      if (question) question.textContent = isEn()?"BEFORE BUILDING OR CHANGING A SYSTEM, WHAT MUST WE UNDERSTAND AND WHAT MUST WE PROVE?":"ANTES DE CONSTRUIR O CAMBIAR UN SISTEMA, ¿QUÉ DEBEMOS COMPRENDER Y QUÉ DEBEMOS COMPROBAR?";
      if (copy) copy.textContent = isEn()?"Week 1 moves from orientation and system understanding to investigation, business case and a responsible decision.":"La Semana 1 avanza desde la orientación y comprensión del sistema hasta la investigación, el caso de negocio y una decisión responsable.";
      let toggle = root.querySelector(".w1f-lens-toggle");
      if (!toggle) {
        toggle = document.createElement("div");
        toggle.className = "w1f-lens-toggle";
        intro.insertAdjacentElement("afterend", toggle);
      }
      toggle.innerHTML = `<span>${isEn()?"VIEW":"VISTA"}</span><button type="button" data-w1f-lens="base" class="${aiOn?"":"is-active"}">BASE</button><button type="button" data-w1f-lens="ai" class="${aiOn?"is-active":""}">${isEn()?"AI LENS":"CAPA IA"}</button><small>${isEn()?"Optional overlay · not a replacement":"Capa opcional · no reemplaza el modelo"}</small>`;
    }
    root.classList.toggle("is-ai-lens", aiOn);
    const figures = [...root.querySelectorAll(".lesson-diagram")].slice(0,7);
    const data = diagramData();
    figures.forEach((figure,i) => {
      const d = data[i];
      const heading = figure.querySelector(".diagram-heading");
      const stage = figure.querySelector(".diagram-stage");
      const caption = figure.querySelector("figcaption");
      if (heading) heading.innerHTML = `<small>DIAGRAM ${String(i+1).padStart(2,"0")}</small><h3>${d.title}</h3>`;
      if (stage) { stage.className = `diagram-stage w1f-stage ${d.cls}`; stage.innerHTML = d.html; }
      if (caption) caption.innerHTML = `<span>${d.caption}</span>${sourceLine()}`;
    });
    renderChecks(root);
    validate(root);
  };

  const validate = root => {
    const used = [...root.querySelectorAll("[data-w1f-key]")].map(n=>n.dataset.w1fKey);
    const unresolved = [...new Set(used.filter(k=>!C[k]))];
    const schema = ["short_definition","why_it_matters","guiding_question","metaphor","examples","related_concepts","not_to_confuse_with","academic_source","ai_lens"];
    const incomplete = [...new Set(used.filter(k=>C[k] && schema.some(field=>C[k][field] == null)))];
    const domainMissing = [...new Set(used.filter(k=>C[k] && domains.some(domain=>!C[k].examples?.[domain])))];
    window.CST212_WEEK1_FINAL_VALIDATION = { diagrams: root.querySelectorAll(".lesson-diagram").length, node_instances: used.length, unique_keys: new Set(used).size, unresolved_keys: unresolved, incomplete_schema: incomplete, missing_example_domains: domainMissing, passed: !unresolved.length && !incomplete.length && !domainMissing.length };
    root.dataset.validation = window.CST212_WEEK1_FINAL_VALIDATION.passed ? "passed" : "failed";
  };

  const ensureUI = () => {
    if (!document.querySelector(".w1f-popover")) document.body.insertAdjacentHTML("beforeend", `<aside class="w1f-popover" hidden></aside><section class="w1f-drawer" hidden aria-modal="true" role="dialog"><button class="w1f-drawer-close" type="button" data-w1f-close aria-label="${isEn()?"Close":"Cerrar"}">×</button><div class="w1f-drawer-content"></div></section>`);
  };
  const placePopover = (node, pop) => {
    const r = node.getBoundingClientRect();
    const width = Math.min(370, window.innerWidth - 24);
    let left = Math.max(12, Math.min(window.innerWidth - width - 12, r.left + r.width/2 - width/2));
    let top = r.bottom + 12;
    if (top + 330 > window.innerHeight) top = Math.max(12, r.top - 318);
    Object.assign(pop.style,{width:`${width}px`,left:`${left}px`,top:`${top}px`});
  };
  const openPopover = (node, concept) => {
    ensureUI();
    const pop = document.querySelector(".w1f-popover");
    pop.innerHTML = `<small>CST212 · WEEK 1</small><h4>${T(concept.title)}</h4><dl><dt>${isEn()?"WHAT IS IT?":"¿QUÉ ES?"}</dt><dd>${T(concept.short_definition)}</dd><dt>${isEn()?"WHY IT MATTERS":"POR QUÉ IMPORTA"}</dt><dd>${T(concept.why_it_matters)}</dd><dt>${isEn()?"METAPHOR":"METÁFORA"}</dt><dd>${T(concept.metaphor)}</dd></dl><button type="button" data-w1f-explore="${concept.key}">${isEn()?"Explore deeper":"Explorar más"} →</button>`;
    pop.hidden = false;
    placePopover(node,pop);
  };
  const openDrawer = concept => {
    ensureUI();
    const drawer = document.querySelector(".w1f-drawer");
    const source = concept.academic_source;
    drawer.querySelector(".w1f-drawer-content").innerHTML = `<header><small>CST212 · WEEK 1</small><h2>${T(concept.title)}</h2></header><div class="w1f-detail-grid"><section><b>01 ${isEn()?"WHAT IS IT?":"¿QUÉ ES?"}</b><p>${T(concept.short_definition)}</p></section><section><b>02 ${isEn()?"WHY DOES IT MATTER?":"¿POR QUÉ IMPORTA?"}</b><p>${T(concept.why_it_matters)}</p></section><section><b>03 ${isEn()?"GUIDING QUESTION":"PREGUNTA GUÍA"}</b><p>${T(concept.guiding_question)}</p></section><section><b>04 ${isEn()?"METAPHOR":"METÁFORA"}</b><p>${T(concept.metaphor)}</p></section><section class="w1f-examples"><b>05 ${isEn()?"EXAMPLES":"EJEMPLOS"}</b><div class="w1f-example-tabs">${domains.map((d,i)=>`<button type="button" data-w1f-domain="${d}" class="${i?"":"is-active"}">${T(domainNames[d])}</button>`).join("")}</div>${domains.map((d,i)=>`<p data-w1f-example="${d}" ${i?"hidden":""}>${T(concept.examples[d])}</p>`).join("")}</section><section><b>06 ${isEn()?"RELATED CONCEPTS":"CONCEPTOS RELACIONADOS"}</b><p>${concept.related_concepts.map(k=>C[k]?T(C[k].title):k).join(" · ") || (isEn()?"No direct links recorded.":"Sin relaciones directas registradas.")}</p></section><section><b>07 ${isEn()?"DO NOT CONFUSE WITH":"NO CONFUNDIR CON"}</b><p>${T(concept.not_to_confuse_with)}</p></section><section><b>08 ${isEn()?"ACADEMIC SOURCE":"FUENTE ACADÉMICA"}</b><p>${source.source_title} · ${source.course_week}<br><a href="${source.canonical_url}" target="_blank" rel="noopener">${source.status}</a></p></section><section class="w1f-ai-detail"><b>09 ${isEn()?"AI LENS":"CAPA IA"}</b><p>${T(concept.ai_lens)}</p><small>AI-FIRST EXTENSION · NOT CST212 CANONICAL</small></section></div>`;
    drawer.hidden = false;
    document.body.classList.add("w1f-drawer-open");
    document.querySelector(".w1f-popover").hidden = true;
  };

  document.addEventListener("pointerover", e => {
    const node = e.target.closest?.("[data-w1f-key]");
    if (!node || !C[node.dataset.w1fKey]) return;
    const related = C[node.dataset.w1fKey].related_concepts;
    node.closest(".w1f-stage")?.querySelectorAll("[data-w1f-key]").forEach(n=>n.classList.toggle("is-related",related.includes(n.dataset.w1fKey)));
  });
  document.addEventListener("pointerout", e => {
    if (!e.target.closest?.("[data-w1f-key]")) return;
    e.target.closest(".w1f-stage")?.querySelectorAll(".is-related").forEach(n=>n.classList.remove("is-related"));
  });
  document.addEventListener("click", e => {
    if (e.target.closest?.(".d1c-stage")) return;
    const lens = e.target.closest?.("[data-w1f-lens]");
    if (lens) {
      aiOn = lens.dataset.w1fLens === "ai";
      const root = document.querySelector("#week-1");
      if (!root) return;
      root.classList.toggle("is-ai-lens", aiOn);
      root.querySelectorAll("[data-w1f-lens]").forEach(button => {
        button.classList.toggle("is-active", button.dataset.w1fLens === (aiOn ? "ai" : "base"));
        button.setAttribute("aria-pressed", String(button.dataset.w1fLens === (aiOn ? "ai" : "base")));
      });
      root.dispatchEvent(new CustomEvent("cst212:lenschange", { detail: { mode: aiOn ? "ai" : "base" } }));
      return;
    }
    const answer = e.target.closest?.("[data-w1f-answer]");
    if (answer) { const q=answer.closest(".w1f-quiz"), correct=Number(answer.dataset.w1fAnswer)===Number(q.dataset.answer), data=quizzes()[Number(q.dataset.quiz)]; q.querySelectorAll("button").forEach(b=>{b.disabled=true;b.classList.toggle("is-correct",Number(b.dataset.w1fAnswer)===data[2]);}); q.querySelector("output").innerHTML=`<b>${correct?(isEn()?"Correct":"Correcto"):(isEn()?"Review":"Revisemos")}</b> ${data[3]}`; return; }
    const domain = e.target.closest?.("[data-w1f-domain]");
    if (domain) { const wrap=domain.closest(".w1f-examples"); wrap.querySelectorAll("[data-w1f-domain]").forEach(b=>b.classList.toggle("is-active",b===domain)); wrap.querySelectorAll("[data-w1f-example]").forEach(p=>p.hidden=p.dataset.w1fExample!==domain.dataset.w1fDomain); return; }
    if (e.target.closest?.("[data-w1f-close]")) { document.querySelector(".w1f-drawer").hidden=true; document.body.classList.remove("w1f-drawer-open"); return; }
    const explore = e.target.closest?.("[data-w1f-explore]");
    if (explore) { openDrawer(C[explore.dataset.w1fExplore]); return; }
    const node = e.target.closest?.("[data-w1f-key]");
    if (node && C[node.dataset.w1fKey]) { e.preventDefault(); e.stopPropagation(); openPopover(node,C[node.dataset.w1fKey]); return; }
    if (!e.target.closest?.(".w1f-popover")) { const p=document.querySelector(".w1f-popover"); if(p)p.hidden=true; }
  }, true);
  document.addEventListener("keydown", e => { if(e.key==="Escape"){ document.querySelector(".w1f-popover")?.setAttribute("hidden",""); const d=document.querySelector(".w1f-drawer"); if(d)d.hidden=true; document.body.classList.remove("w1f-drawer-open"); } });

  const boot = () => { ensureUI(); renderWeek(); };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded",boot,{once:true}); else boot();
  const finalDiagramSelector = ".d1c-stage, .d1c-drawer, .d1c-backdrop, .w1i-lens-slot, .d1a-ai-node, .d1a-paths, .d1a-state-message, .d1a-drawer, .d1a-backdrop";
  const isFinalDiagramMutation = mutation => {
    if (mutation.target.closest?.(finalDiagramSelector)) return true;
    const changedElements = [...mutation.addedNodes, ...mutation.removedNodes]
      .filter(node => node.nodeType === 1);
    return changedElements.length > 0 && changedElements.every(node =>
      node.matches?.(finalDiagramSelector) || node.closest?.(finalDiagramSelector)
    );
  };
  new MutationObserver(mutations => {
    if (mutations.length && mutations.every(isFinalDiagramMutation)) return;
    requestAnimationFrame(renderWeek);
  }).observe(document.documentElement,{childList:true,subtree:true});
})();
